#!/bin/bash

VERSION=0.0.2
PACKAGE=1
ARCHS="amd64 i386"

set -e

for ARCH in ${ARCHS}; do

# Remove the existing package

rm -f ./trickplay-sdk_${VERSION}-${PACKAGE}_${ARCH}.deb 

# Write the control file

rm -rf ./trickplay-sdk_${ARCH}

mkdir -p ./trickplay-sdk_${ARCH}/DEBIAN
mkdir -p ./trickplay-sdk_${ARCH}/usr/bin
mkdir -p ./trickplay-sdk_${ARCH}/usr/share/doc
mkdir -p ./trickplay-sdk_${ARCH}/usr/share/man/man1
mkdir -p ./trickplay-sdk_${ARCH}/usr/share/doc/trickplay-sdk

cp ./trickplay.${ARCH} ./trickplay-sdk_${ARCH}/usr/bin/trickplay

cat << CONTROL_END > ./trickplay-sdk_${ARCH}/DEBIAN/control
Package: trickplay-sdk
Version: ${VERSION}-${PACKAGE}
Architecture: ${ARCH}
Maintainer: Pablo Pissanetzky <pablo@trickplay.com>
Installed-Size: 1500
Depends: libc6 (>= 2.7), libcairo2 (>= 1.4.10), libgl1-mesa-glx | libgl1, libglib2.0-0 (>= 2.18.0), libgtk2.0-0 (>= 2.8.0), libpango1.0-0 (>= 1.20.0), libx11-6, libxcomposite1 (>= 1:0.3-1), libxdamage1 (>= 1:1.1), libxext6, libxfixes3 (>= 1:4.0.1), libcurl3 (>=7.19.0), libavahi-common3 (>= 0.6.25), libavahi-core6 (>= 0.6.25), libavahi-glib1(>= 0.6.25), libclutter-1.0-0 (>= 1.0.6), libtokyocabinet8, libexpat1, libsqlite3-0 (>= 3.6.0), libclutter-gst-0.10-0, libtiff4, libjson-glib-1.0-0 (>= 0.5.0), libjpeg62, libtiffxx0c2
Section: non-free/devel
Priority: optional
Description: TrickPlay SDK
 The TrickPlay SDK allows you to build and test TrickPlay apps.
CONTROL_END

# Write the changelog

gzip --best -c changelog > ./trickplay-sdk_${ARCH}/usr/share/doc/trickplay-sdk/changelog.gz

# Write the Debian changelog

gzip --best -c changelog > ./trickplay-sdk_${ARCH}/usr/share/doc/trickplay-sdk/changelog.Debian.gz

# Generate the man page

pod2man -c "TrickPlay SDK" -r "TrickPlay ${VERSION}" ./trickplay.1.pod | gzip --best > ./trickplay-sdk_${ARCH}/usr/share/man/man1/trickplay.1.gz

# Copy the documentation

cp -r ./html ./trickplay-sdk_${ARCH}/usr/share/doc/trickplay-sdk/

# Copyright file

cp ./copyright ./trickplay-sdk_${ARCH}/usr/share/doc/trickplay-sdk/

# Build the package

fakeroot dpkg-deb --build ./trickplay-sdk_${ARCH} ./trickplay-sdk_${VERSION}-${PACKAGE}_${ARCH}.deb 

# Run it through lintian
# The '|| true' forces a success return until we deal with the lintian errors.

lintian -v ./trickplay-sdk_${VERSION}-${PACKAGE}_${ARCH}.deb || true

done


