# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Wed Nov  9 10:43:09 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(1000, 834)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setCursor(QtCore.Qt.ArrowCursor)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        MainWindow.setMenuBar(self.menubar)
        self.InspectorDock = QtGui.QDockWidget(MainWindow)
        self.InspectorDock.setEnabled(True)
        self.InspectorDock.setMinimumSize(QtCore.QSize(300, 45))
        self.InspectorDock.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.InspectorDock.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.InspectorDock.setObjectName(_fromUtf8("InspectorDock"))
        self.InspectorContainer = QtGui.QWidget()
        self.InspectorContainer.setObjectName(_fromUtf8("InspectorContainer"))
        self.gridLayout_2 = QtGui.QGridLayout(self.InspectorContainer)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.InspectorLayout = QtGui.QGridLayout()
        self.InspectorLayout.setObjectName(_fromUtf8("InspectorLayout"))
        self.gridLayout_2.addLayout(self.InspectorLayout, 0, 0, 1, 1)
        self.InspectorDock.setWidget(self.InspectorContainer)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.InspectorDock)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.DeviceManagerDock = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DeviceManagerDock.sizePolicy().hasHeightForWidth())
        self.DeviceManagerDock.setSizePolicy(sizePolicy)
        self.DeviceManagerDock.setMinimumSize(QtCore.QSize(100, 163))
        self.DeviceManagerDock.setObjectName(_fromUtf8("DeviceManagerDock"))
        self.DeviceManagerContainer = QtGui.QWidget()
        self.DeviceManagerContainer.setObjectName(_fromUtf8("DeviceManagerContainer"))
        self.verticalLayout = QtGui.QVBoxLayout(self.DeviceManagerContainer)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.DeviceManagerLayout = QtGui.QGridLayout()
        self.DeviceManagerLayout.setObjectName(_fromUtf8("DeviceManagerLayout"))
        self.verticalLayout.addLayout(self.DeviceManagerLayout)
        self.DeviceManagerDock.setWidget(self.DeviceManagerContainer)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.DeviceManagerDock)
        self.FileSystemDock = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FileSystemDock.sizePolicy().hasHeightForWidth())
        self.FileSystemDock.setSizePolicy(sizePolicy)
        self.FileSystemDock.setFloating(False)
        self.FileSystemDock.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.FileSystemDock.setObjectName(_fromUtf8("FileSystemDock"))
        self.FileSystemContainer = QtGui.QWidget()
        self.FileSystemContainer.setObjectName(_fromUtf8("FileSystemContainer"))
        self.gridLayout_3 = QtGui.QGridLayout(self.FileSystemContainer)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.FileSystemLayout = QtGui.QGridLayout()
        self.FileSystemLayout.setObjectName(_fromUtf8("FileSystemLayout"))
        self.gridLayout_3.addLayout(self.FileSystemLayout, 0, 0, 1, 1)
        self.FileSystemDock.setWidget(self.FileSystemContainer)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.FileSystemDock)
        self.ConsoleDock = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ConsoleDock.sizePolicy().hasHeightForWidth())
        self.ConsoleDock.setSizePolicy(sizePolicy)
        self.ConsoleDock.setFloating(False)
        self.ConsoleDock.setObjectName(_fromUtf8("ConsoleDock"))
        self.ConsoleContainer = QtGui.QWidget()
        self.ConsoleContainer.setObjectName(_fromUtf8("ConsoleContainer"))
        self.gridLayout = QtGui.QGridLayout(self.ConsoleContainer)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.ConsoleLayout = QtGui.QGridLayout()
        self.ConsoleLayout.setObjectName(_fromUtf8("ConsoleLayout"))
        self.gridLayout.addLayout(self.ConsoleLayout, 0, 0, 1, 1)
        self.ConsoleDock.setWidget(self.ConsoleContainer)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.ConsoleDock)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.action_Exit = QtGui.QAction(MainWindow)
        self.action_Exit.setMenuRole(QtGui.QAction.QuitRole)
        self.action_Exit.setObjectName(_fromUtf8("action_Exit"))
        self.action_Save = QtGui.QAction(MainWindow)
        self.action_Save.setObjectName(_fromUtf8("action_Save"))
        self.action_New = QtGui.QAction(MainWindow)
        self.action_New.setObjectName(_fromUtf8("action_New"))
        self.action_Cut = QtGui.QAction(MainWindow)
        self.action_Cut.setObjectName(_fromUtf8("action_Cut"))
        self.action_Copy = QtGui.QAction(MainWindow)
        self.action_Copy.setObjectName(_fromUtf8("action_Copy"))
        self.action_Paste = QtGui.QAction(MainWindow)
        self.action_Paste.setObjectName(_fromUtf8("action_Paste"))
        self.action_Delete = QtGui.QAction(MainWindow)
        self.action_Delete.setObjectName(_fromUtf8("action_Delete"))
        self.actionSelect_All = QtGui.QAction(MainWindow)
        self.actionSelect_All.setObjectName(_fromUtf8("actionSelect_All"))
        self.action_Close = QtGui.QAction(MainWindow)
        self.action_Close.setObjectName(_fromUtf8("action_Close"))
        self.action_Save_As = QtGui.QAction(MainWindow)
        self.action_Save_As.setObjectName(_fromUtf8("action_Save_As"))
        self.menuFile.addAction(self.action_New)
        self.menuFile.addAction(self.action_Save)
        self.menuFile.addAction(self.action_Save_As)
        self.menuFile.addAction(self.action_Close)
        self.menuFile.addAction(self.action_Exit)
        self.menuEdit.addAction(self.action_Cut)
        self.menuEdit.addAction(self.action_Copy)
        self.menuEdit.addAction(self.action_Paste)
        self.menuEdit.addAction(self.action_Delete)
        self.menuEdit.addAction(self.actionSelect_All)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Trickplay Visual Debugger", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.InspectorDock.setWindowTitle(QtGui.QApplication.translate("MainWindow", "  Inspector", None, QtGui.QApplication.UnicodeUTF8))
        self.DeviceManagerDock.setWindowTitle(QtGui.QApplication.translate("MainWindow", "  Device Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.FileSystemDock.setWindowTitle(QtGui.QApplication.translate("MainWindow", "  File System", "texty7", QtGui.QApplication.UnicodeUTF8))
        self.ConsoleDock.setWindowTitle(QtGui.QApplication.translate("MainWindow", "  Console", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Exit.setText(QtGui.QApplication.translate("MainWindow", "&Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Exit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save.setText(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.action_New.setText(QtGui.QApplication.translate("MainWindow", "&New", None, QtGui.QApplication.UnicodeUTF8))
        self.action_New.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Cut.setText(QtGui.QApplication.translate("MainWindow", "&Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Cut.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+X", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Copy.setText(QtGui.QApplication.translate("MainWindow", "C&opy", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Copy.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Paste.setText(QtGui.QApplication.translate("MainWindow", "&Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Paste.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+V", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Delete.setText(QtGui.QApplication.translate("MainWindow", "&Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelect_All.setText(QtGui.QApplication.translate("MainWindow", "Select &All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelect_All.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+A", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Close.setText(QtGui.QApplication.translate("MainWindow", "&Close", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Close.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+W", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save_As.setText(QtGui.QApplication.translate("MainWindow", "Save &As", None, QtGui.QApplication.UnicodeUTF8))

