# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Preference.ui'
#
# Created: Tue Apr 17 11:46:00 2012
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_preferenceDialog(object):
    def setupUi(self, preferenceDialog):
        preferenceDialog.setObjectName(_fromUtf8("preferenceDialog"))
        preferenceDialog.resize(500, 233)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(preferenceDialog.sizePolicy().hasHeightForWidth())
        preferenceDialog.setSizePolicy(sizePolicy)
        preferenceDialog.setMaximumSize(QtCore.QSize(500, 233))
        preferenceDialog.setSizeGripEnabled(False)
        preferenceDialog.setModal(False)
        self.tabWidget = QtGui.QTabWidget(preferenceDialog)
        self.tabWidget.setGeometry(QtCore.QRect(4, 6, 491, 223))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setMouseTracking(True)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Fonts = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Fonts.sizePolicy().hasHeightForWidth())
        self.Fonts.setSizePolicy(sizePolicy)
        self.Fonts.setObjectName(_fromUtf8("Fonts"))
        self.gridLayout_3 = QtGui.QGridLayout(self.Fonts)
        self.gridLayout_3.setMargin(7)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label = QtGui.QLabel(self.Fonts)
        self.label.setIndent(0)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 4, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.Fonts)
        self.label_2.setIndent(0)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.Fonts)
        self.label_3.setIndent(0)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.Fonts)
        self.label_4.setIndent(0)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.Fonts)
        self.label_5.setIndent(0)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_4.addWidget(self.label_5, 1, 0, 1, 1)
        self.variableFont = QtGui.QLineEdit(self.Fonts)
        self.variableFont.setAlignment(QtCore.Qt.AlignCenter)
        self.variableFont.setReadOnly(True)
        self.variableFont.setObjectName(_fromUtf8("variableFont"))
        self.gridLayout_4.addWidget(self.variableFont, 4, 1, 1, 1)
        self.backtraceFont = QtGui.QLineEdit(self.Fonts)
        self.backtraceFont.setAlignment(QtCore.Qt.AlignCenter)
        self.backtraceFont.setReadOnly(True)
        self.backtraceFont.setObjectName(_fromUtf8("backtraceFont"))
        self.gridLayout_4.addWidget(self.backtraceFont, 3, 1, 1, 1)
        self.consoleFont = QtGui.QLineEdit(self.Fonts)
        self.consoleFont.setAlignment(QtCore.Qt.AlignCenter)
        self.consoleFont.setReadOnly(True)
        self.consoleFont.setObjectName(_fromUtf8("consoleFont"))
        self.gridLayout_4.addWidget(self.consoleFont, 2, 1, 1, 1)
        self.inspectorFont = QtGui.QLineEdit(self.Fonts)
        self.inspectorFont.setAlignment(QtCore.Qt.AlignCenter)
        self.inspectorFont.setReadOnly(True)
        self.inspectorFont.setObjectName(_fromUtf8("inspectorFont"))
        self.gridLayout_4.addWidget(self.inspectorFont, 1, 1, 1, 1)
        self.filesystemFont = QtGui.QLineEdit(self.Fonts)
        self.filesystemFont.setEnabled(True)
        self.filesystemFont.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.filesystemFont.setAlignment(QtCore.Qt.AlignCenter)
        self.filesystemFont.setReadOnly(True)
        self.filesystemFont.setObjectName(_fromUtf8("filesystemFont"))
        self.gridLayout_4.addWidget(self.filesystemFont, 0, 1, 1, 1)
        self.inspectorSelect = QtGui.QPushButton(self.Fonts)
        self.inspectorSelect.setObjectName(_fromUtf8("inspectorSelect"))
        self.gridLayout_4.addWidget(self.inspectorSelect, 1, 2, 1, 1)
        self.consoleSelect = QtGui.QPushButton(self.Fonts)
        self.consoleSelect.setObjectName(_fromUtf8("consoleSelect"))
        self.gridLayout_4.addWidget(self.consoleSelect, 2, 2, 1, 1)
        self.backtraceSelect = QtGui.QPushButton(self.Fonts)
        self.backtraceSelect.setObjectName(_fromUtf8("backtraceSelect"))
        self.gridLayout_4.addWidget(self.backtraceSelect, 3, 2, 1, 1)
        self.variableSelect = QtGui.QPushButton(self.Fonts)
        self.variableSelect.setObjectName(_fromUtf8("variableSelect"))
        self.gridLayout_4.addWidget(self.variableSelect, 4, 2, 1, 1)
        self.fileSystemSelect = QtGui.QPushButton(self.Fonts)
        self.fileSystemSelect.setObjectName(_fromUtf8("fileSystemSelect"))
        self.gridLayout_4.addWidget(self.fileSystemSelect, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.Fonts, _fromUtf8(""))
        self.EditorStyle = QtGui.QWidget()
        self.EditorStyle.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EditorStyle.sizePolicy().hasHeightForWidth())
        self.EditorStyle.setSizePolicy(sizePolicy)
        self.EditorStyle.setObjectName(_fromUtf8("EditorStyle"))
        self.gridLayout_2 = QtGui.QGridLayout(self.EditorStyle)
        self.gridLayout_2.setMargin(7)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(12)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.tableWidget = QtGui.QTableWidget(self.EditorStyle)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setRowCount(15)
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(15)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setHighlightSections(False)
        self.horizontalLayout_5.addWidget(self.tableWidget)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_6 = QtGui.QLabel(self.EditorStyle)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_4.addWidget(self.label_6)
        self.descriptionText = QtGui.QTextBrowser(self.EditorStyle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.descriptionText.sizePolicy().hasHeightForWidth())
        self.descriptionText.setSizePolicy(sizePolicy)
        self.descriptionText.setObjectName(_fromUtf8("descriptionText"))
        self.verticalLayout_4.addWidget(self.descriptionText)
        self.label_7 = QtGui.QLabel(self.EditorStyle)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_4.addWidget(self.label_7)
        self.previewText = QtGui.QTextBrowser(self.EditorStyle)
        self.previewText.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.previewText.setObjectName(_fromUtf8("previewText"))
        self.verticalLayout_4.addWidget(self.previewText)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.fontSelect = QtGui.QPushButton(self.EditorStyle)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fontSelect.setFont(font)
        self.fontSelect.setObjectName(_fromUtf8("fontSelect"))
        self.horizontalLayout_7.addWidget(self.fontSelect)
        self.bColorSelect = QtGui.QPushButton(self.EditorStyle)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bColorSelect.setFont(font)
        self.bColorSelect.setObjectName(_fromUtf8("bColorSelect"))
        self.horizontalLayout_7.addWidget(self.bColorSelect)
        self.fColorSelect = QtGui.QPushButton(self.EditorStyle)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fColorSelect.setFont(font)
        self.fColorSelect.setObjectName(_fromUtf8("fColorSelect"))
        self.horizontalLayout_7.addWidget(self.fColorSelect)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.EditorStyle, _fromUtf8(""))

        self.retranslateUi(preferenceDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(preferenceDialog)

    def retranslateUi(self, preferenceDialog):
        preferenceDialog.setWindowTitle(QtGui.QApplication.translate("preferenceDialog", "Preference", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("preferenceDialog", "Variables/Break Points:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("preferenceDialog", "FileSystem:                      ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("preferenceDialog", "BackTrace:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("preferenceDialog", "Console:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("preferenceDialog", "Inspector:", None, QtGui.QApplication.UnicodeUTF8))
        self.inspectorSelect.setText(QtGui.QApplication.translate("preferenceDialog", "Select...", None, QtGui.QApplication.UnicodeUTF8))
        self.consoleSelect.setText(QtGui.QApplication.translate("preferenceDialog", "Select...", None, QtGui.QApplication.UnicodeUTF8))
        self.backtraceSelect.setText(QtGui.QApplication.translate("preferenceDialog", "Select...", None, QtGui.QApplication.UnicodeUTF8))
        self.variableSelect.setText(QtGui.QApplication.translate("preferenceDialog", "Select...", None, QtGui.QApplication.UnicodeUTF8))
        self.fileSystemSelect.setText(QtGui.QApplication.translate("preferenceDialog", "Select...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Fonts), QtGui.QApplication.translate("preferenceDialog", " Fonts", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("preferenceDialog", "Description:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("preferenceDialog", "Preview:", None, QtGui.QApplication.UnicodeUTF8))
        self.fontSelect.setText(QtGui.QApplication.translate("preferenceDialog", "Select Font...", None, QtGui.QApplication.UnicodeUTF8))
        self.bColorSelect.setText(QtGui.QApplication.translate("preferenceDialog", "Paper Color...", None, QtGui.QApplication.UnicodeUTF8))
        self.fColorSelect.setText(QtGui.QApplication.translate("preferenceDialog", "Text Color...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.EditorStyle), QtGui.QApplication.translate("preferenceDialog", "Editor Style", None, QtGui.QApplication.UnicodeUTF8))

