# - Find PANGO
# Find the native PANGO headers and libraries.
#

# Look for the header file.
FIND_PATH(PANGO_INCLUDE_DIR NAMES pango-1.0)
MARK_AS_ADVANCED(PANGO_INCLUDE_DIR)

# Look for the library.
FIND_LIBRARY(PANGO_LIBRARY NAMES pango-1.0)
MARK_AS_ADVANCED(PANGO_LIBRARY)

# handle the QUIETLY and REQUIRED arguments and set PANGO_FOUND to TRUE if 
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(PANGO DEFAULT_MSG PANGO_LIBRARY PANGO_INCLUDE_DIR)

IF(PANGO_FOUND)
  SET(PANGO_LIBRARIES ${PANGO_LIBRARY})
  SET(PANGO_INCLUDE_DIRS ${PANGO_INCLUDE_DIR}/pango-1.0)
ELSE(PANGO_FOUND)
  SET(PANGO_LIBRARIES)
  SET(PANGO_INCLUDE_DIRS)
ENDIF(PANGO_FOUND)
