dofile("views/ButtonView.lua")
dofile("views/DogView.lua")
dofile("views/SeatButtonView.lua")
dofile("views/SplashView.lua")
dofile("controllers/SplashController.lua")
dofile("views/CharacterSelectionView.lua")
dofile("controllers/CharacterSelectionController.lua")
