//
//  SIPDialog.h
//  VideoSIP
//
//  Created by Rex Fenley on 3/1/12.
//  Copyright (c) 2012 __MyCompanyName__. All rights reserved.
//

#import <Foundation/Foundation.h>

#import <sys/types.h>
#import <netinet/in.h>
#import <sys/socket.h>


@class VideoStreamerContext;
@class SIPDialog;

/**
 * The SIPDialogDelegate protocol is used by SIPDialog Objects to inform a delegate
 * (likely a SIPClient object) of data (SIP Requests/Responses) to send over the
 * network. Additionally, this protocol informs the delegate of when a new Dialog
 * Session begins/ends and when a Call has been established/ended, thus, indicating time
 * to begin/end an RTP stream for the Call.
 *
 * SIPDialog Objects are only capable of forming and disassembling SIP packets and
 * interpretting SIP packets. This protocol is used to send SIP packets assembled by
 * the SIPDialog (I.E. SIPDialog assembles an INVITE packet and needs to send it
 * over the network) or to inform the delegate of actions to be taken based off of a
 * parsed SIP packet (I.E. a BYE packet was received and therefore the delegate should
 * close an associated RTP stream).
 */

@protocol SIPDialogDelegate <NSObject>
@required
- (void)dialogSessionStarted:(SIPDialog *)dialog;
- (void)dialogSessionEnded:(SIPDialog *)dialog;
- (void)dialog:(SIPDialog *)dialog beganRTPStreamWithMediaDestination:(NSDictionary *)mediaDest;
- (void)dialog:(SIPDialog *)dialog endRTPStreamWithMediaDestination:(NSDictionary *)mediaDest;
- (void)dialog:(SIPDialog *)dialog wantsToSendData:(NSData *)data;

@end

/**
 * SIPDialog is an abstract class for all SIP packet types. INVITE, REGISTER, OPTIONS, etc.
 * packets are all created via SIPDialog subclasses. These subclasses peform the task of
 * forming SIP Request/Response packets to send over the network, parsing received SIP
 * Requests and/or Responses, and interpretting the received SIP packets.
 *
 * SIPDialog objects do not natively have any network architecture, but rely on delegate methods
 * to inform a delegate (likely a SIPClient) of what information has been interpretted.
 * Additionally, SIPDialog objects may build Request and/or Response packets and hand them
 * off to the delegate assuming the delegate should have the required network architecture
 * to send the Request and/or Response packets to the required destination.
 *
 * Refer to RFC 3261 - SIP:Session Initiation Protocol for more information.
 */

@interface SIPDialog : NSObject {
    // This is our user name
    NSString *user;
    // This is our contact URI
    NSString *contactURI;
    // This is the original destination URI; do not change
    NSString *remoteURI;
    // This is the dynamic destination URI; this is not constant.
    // Used in the Request line and the MD5 authentication.
    // This URI will be updated as SIP discovers the final
    // destination URI.
    NSString *sipURI;
    // This is our IP address
    NSString *clientPrivateIP;
    // This is the public IP address discovered via STUN
    NSString *clientPublicIP;
    // This is our SIP port
    u_int32_t udpClientPort;
    // This is the destination SIP port
    u_int32_t udpServerPort;
    
    // Used to record the SIP route taken by a request and
    // used to route the response back to the originator.
    // UAs generating a request records its own address in a Via
    // and adds it to the header.
    // Order of Via header fields is significant as it determines routes
    NSMutableDictionary *via;
    // How many times can this packet bounce around the network.
    NSUInteger maxForwards;
    // Where are my Requests sending from?
    // tag is generated locally from the UAC.
    // TODO: use a different hash function for generation
    NSMutableDictionary *from;
    // Where are my Requests going?
    // tag is generated by UAS.
    NSMutableDictionary *to;
    // All Calls are tied to a specific Call-ID. OPTIONS always
    // has a unique Call-ID. All REGISTER Requests from the same
    // UA have the same Call-ID.
    NSString *callID;
    // Sequence Number; increments per request for same call.
    // Exception is ACK or CANCEL where it uses the CSeq number
    // of the INVITE it's referencing.
    NSUInteger cseq;
    // This is your routable address. The SIP Server caches this and
    // and forwards all outside requests to this address therefore this
    // must reference your address outside the NAT. All INVITES and 200
    // responses must have a Contact. REGISTER Requests may have
    // Contact: * to remove all existing Registrations.
    NSString *contact;
    // A useless name you can include, may help with logs on server side.
    NSString *userAgent;
    // These are the Requests we allow. All of these should be
    // implemented to complete this project.
    NSString *allow;
    // This is additional stuff you support. NOTE: we currently dont'
    // support any of it, but SIP packets analyzed from other sources
    // all seem to have this so we'll include it for now
    NSString *supported;
    // SIP branch. Every Dialog has a branch transaction ID
    NSString *branch;
    // This is the line you put in the authorization during
    // REGISTER or INVITE requests
    NSString *authLine;
    // This contains all the data (passwords, md5, etc.) to form
    // authLine.
    NSMutableDictionary *auth;
    
    // Delegate to SIPClient
    id <SIPDialogDelegate> delegate;
}

//properties

@property (nonatomic, retain) NSString *user;
@property (nonatomic, retain) NSString *contactURI;
@property (nonatomic, retain) NSString *remoteURI;
@property (nonatomic, retain) NSString *sipURI;
@property (nonatomic, retain) NSString *clientPublicIP;
@property (nonatomic, retain) NSString *clientPrivateIP;
@property (assign) u_int32_t udpClientPort;
@property (assign) u_int32_t udpServerPort;
@property (nonatomic, retain) NSMutableDictionary *via;
@property (assign) NSUInteger maxForwards;
@property (nonatomic, retain) NSMutableDictionary *from;
@property (nonatomic, retain) NSMutableDictionary *to;
@property (nonatomic, retain) NSString *callID;
@property (assign) NSUInteger cseq;
@property (nonatomic, retain) NSString *contact;
@property (nonatomic, retain) NSString *userAgent;
@property (nonatomic, retain) NSString *allow;
@property (nonatomic, retain) NSString *supported;
@property (nonatomic, retain) NSString *branch;
@property (nonatomic, retain) NSString *authLine;
@property (nonatomic, retain) NSMutableDictionary *auth;

@property (nonatomic, assign) id <SIPDialogDelegate> delegate;


// methods

- (id)initWithVideoStreamerContext:(VideoStreamerContext *)_context clientPublicIP:(NSString *)_clientPublicIP clientPrivateIP:(NSString *)_clientPrivateIP delegate:(id <SIPDialogDelegate>)_delegate;
// Interpret a parsed SIP packet and do something
- (void)interpretSIP:(NSDictionary *)parsedPacket body:(NSString *)body fromAddr:(NSData *)remoteAddr;
// Cancel this dialog. Not all dialogs cancel, and should overwrite this function
- (void)cancel;

@end



#pragma mark -
#pragma mark REGISTER

/**
 * REGISTER is used to register to the SIP server. This lets the
 * SIP server know that I am a user of SIP and that I am alive
 * and ready to make and receive calls.
 */

@interface RegisterDialog : SIPDialog

- (void)registerToAsteriskWithCallID:(NSString *)registerCallID;

@end

#pragma mark -
#pragma mark OPTIONS

/**
 * The server will send OPTIONS packets either as keep-alives or
 * to discover what this SIP client is capable of. I just return
 * 200 OK packets to shut it up.
 */

@interface OptionsDialog : SIPDialog

- (void)receivedOptions:(NSDictionary *)optionsPacket fromAddr:(NSData *)remoteAddr;

@end

#pragma mark -
#pragma mark NOTIFY

/**
 * Not sure why the server sends NOTIFY packets my way, but responding
 * with 200 OK gets the server to shut up.
 */

@interface NotifyDialog : SIPDialog

- (void)receivedNotify:(NSDictionary *)notifyPacket fromAddr:(NSData *)remoteAddr;

@end

#pragma mark -
#pragma mark BYE

/**
 * This class deals with incoming BYE messages that are not associated with
 * any active INVITE dialog. Generally, if a call ended because the server
 * sent BYE to the phone we do not respond fast enough, thus, causing
 * multiple BYE messages to come our way. This class just responds with
 * 481 Dialog/Transaction Does Not Exist to shut the server up.
 */

@interface ByeDialog : SIPDialog

- (void)receivedBye:(NSDictionary *)byePacket fromAddr:(NSData *)remoteAddr;

@end

#pragma mark -
#pragma mark INVITE

/**
 * This class sends an INVITE to the provided destination address, formally
 * initiating a SIP call to begin a media chat.
 *
 * This class can handle WWW-Authentication or Proxy-Authentication with qop.
 */

@interface InviteDialog : SIPDialog {
    NSMutableDictionary *previousAcks;
    
    NSData *sps;
    NSData *pps;
    
    // TODO: Currently the mediaDestination is passed from sipThread to the main thread
    // for use with the video encoder. May instead want to make a copy of mediaDestination
    // and pass the copy to the other thread to prevent possibilities of corrupt read/writes
    NSDictionary *mediaDestination;
}

/**
 * Designated initializer with parameters necessary to initiate a SIP call.
 */
- (id)initWithVideoStreamerContext:(VideoStreamerContext *)_context clientPublicIP:(NSString *)_clientPublicIP clientPrivateIP:(NSString *)_clientPrivateIP sps:(NSData *)_sps pps:(NSData *)_pps delegate:(id <SIPDialogDelegate>)_delegate;

/**
 * Send an invite using the Authorization type provided to key.
 */
- (void)inviteWithAuthHeader:(NSString *)key;

@end





