package trickplay;

/**
 * User domain class. Generated by Grails Acegi plugin, but modified
 * to fix the User/Role many-to-many problem with Hibernate.
 * @author Garth
 */
class User {
    static transients = ['pass'];

    //removed to fix the User/Role many-to-many problem with Hibernate.
    //static hasMany = [authorities: Role];
    //static belongsTo = Role;
    static hasMany = [ paymentProfiles:PaymentProfile, reviews:Review, wishes:Wish ];
    
    String username, userRealName, passwd;
    boolean enabled;
    
    String email;
    boolean emailShow;
    
    String description = '';
    String pass = '[secret]';
    

    Set<Role> getAuthorities() {
        UserRole.findAllByUser(this).collect { it.role } as Set;
    }
    
    boolean hasRole(Role role) {
        UserRole.countByUserAndRole(this, role) > 0;
    }

    static constraints = {
        username(blank: false, unique: true);
        userRealName(blank: true, nullable:true);
        passwd(blank: false);
        enabled();
    }
}
