# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Mon Apr 22 14:34:52 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(527, 391)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 527, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.menubar.setFont(font)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuInsert_UI_Element = QtGui.QMenu(self.menuEdit)
        self.menuInsert_UI_Element.setObjectName(_fromUtf8("menuInsert_UI_Element"))
        self.menuArrange = QtGui.QMenu(self.menubar)
        self.menuArrange.setObjectName(_fromUtf8("menuArrange"))
        self.menu_align = QtGui.QMenu(self.menuArrange)
        self.menu_align.setObjectName(_fromUtf8("menu_align"))
        self.menu_distribute = QtGui.QMenu(self.menuArrange)
        self.menu_distribute.setObjectName(_fromUtf8("menu_distribute"))
        self.menu_arrange = QtGui.QMenu(self.menuArrange)
        self.menu_arrange.setObjectName(_fromUtf8("menu_arrange"))
        self.menuView_2 = QtGui.QMenu(self.menubar)
        self.menuView_2.setObjectName(_fromUtf8("menuView_2"))
        self.menuBackground = QtGui.QMenu(self.menuView_2)
        self.menuBackground.setObjectName(_fromUtf8("menuBackground"))
        MainWindow.setMenuBar(self.menubar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.action_Exit = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        self.action_Exit.setFont(font)
        self.action_Exit.setMenuRole(QtGui.QAction.QuitRole)
        self.action_Exit.setObjectName(_fromUtf8("action_Exit"))
        self.action_Save = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        self.action_Save.setFont(font)
        self.action_Save.setObjectName(_fromUtf8("action_Save"))
        self.action_New = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        self.action_New.setFont(font)
        self.action_New.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.action_New.setObjectName(_fromUtf8("action_New"))
        self.action_Cut = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        self.action_Cut.setFont(font)
        self.action_Cut.setObjectName(_fromUtf8("action_Cut"))
        self.action_Copy = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        self.action_Copy.setFont(font)
        self.action_Copy.setObjectName(_fromUtf8("action_Copy"))
        self.action_Paste = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        self.action_Paste.setFont(font)
        self.action_Paste.setObjectName(_fromUtf8("action_Paste"))
        self.action_Delete = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        self.action_Delete.setFont(font)
        self.action_Delete.setObjectName(_fromUtf8("action_Delete"))
        self.actionSelect_All = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionSelect_All.setFont(font)
        self.actionSelect_All.setObjectName(_fromUtf8("actionSelect_All"))
        self.action_Close = QtGui.QAction(MainWindow)
        self.action_Close.setIconText(_fromUtf8("Close file"))
        font = QtGui.QFont()
        self.action_Close.setFont(font)
        self.action_Close.setObjectName(_fromUtf8("action_Close"))
        self.action_Save_As = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        self.action_Save_As.setFont(font)
        self.action_Save_As.setObjectName(_fromUtf8("action_Save_As"))
        self.actionUndo = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionUndo.setFont(font)
        self.actionUndo.setObjectName(_fromUtf8("actionUndo"))
        self.actionRedo = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionRedo.setFont(font)
        self.actionRedo.setObjectName(_fromUtf8("actionRedo"))
        self.actionDebug = QtGui.QAction(MainWindow)
        self.actionDebug.setObjectName(_fromUtf8("actionDebug"))
        self.actionRun = QtGui.QAction(MainWindow)
        self.actionRun.setObjectName(_fromUtf8("actionRun"))
        self.actionStep_into = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionStep_into.setFont(font)
        self.actionStep_into.setObjectName(_fromUtf8("actionStep_into"))
        self.actionStep_over = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionStep_over.setFont(font)
        self.actionStep_over.setObjectName(_fromUtf8("actionStep_over"))
        self.actionDebug_View = QtGui.QAction(MainWindow)
        self.actionDebug_View.setObjectName(_fromUtf8("actionDebug_View"))
        self.actionRun_View = QtGui.QAction(MainWindow)
        self.actionRun_View.setObjectName(_fromUtf8("actionRun_View"))
        self.actionSave_All = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionSave_All.setFont(font)
        self.actionSave_All.setObjectName(_fromUtf8("actionSave_All"))
        self.actionSearch = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionSearch.setFont(font)
        self.actionSearch.setObjectName(_fromUtf8("actionSearch"))
        self.actionSearch_Replace = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionSearch_Replace.setFont(font)
        self.actionSearch_Replace.setObjectName(_fromUtf8("actionSearch_Replace"))
        self.actionGo_to_line = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionGo_to_line.setFont(font)
        self.actionGo_to_line.setObjectName(_fromUtf8("actionGo_to_line"))
        self.actionSearch_in_Files = QtGui.QAction(MainWindow)
        self.actionSearch_in_Files.setObjectName(_fromUtf8("actionSearch_in_Files"))
        self.actionBeutify_Selection = QtGui.QAction(MainWindow)
        self.actionBeutify_Selection.setObjectName(_fromUtf8("actionBeutify_Selection"))
        self.actionStrip_Whitespace = QtGui.QAction(MainWindow)
        self.actionStrip_Whitespace.setObjectName(_fromUtf8("actionStrip_Whitespace"))
        self.actionStep_out = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionStep_out.setFont(font)
        self.actionStep_out.setObjectName(_fromUtf8("actionStep_out"))
        self.actionStop = QtGui.QAction(MainWindow)
        self.actionStop.setObjectName(_fromUtf8("actionStop"))
        self.actionPause = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionPause.setFont(font)
        self.actionPause.setObjectName(_fromUtf8("actionPause"))
        self.actionContinue = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionContinue.setFont(font)
        self.actionContinue.setObjectName(_fromUtf8("actionContinue"))
        self.actionNew_File = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionNew_File.setFont(font)
        self.actionNew_File.setObjectName(_fromUtf8("actionNew_File"))
        self.actionNew_Folder = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionNew_Folder.setFont(font)
        self.actionNew_Folder.setObjectName(_fromUtf8("actionNew_Folder"))
        self.actionOpen_App = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionOpen_App.setFont(font)
        self.actionOpen_App.setObjectName(_fromUtf8("actionOpen_App"))
        self.actionNew_App = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionNew_App.setFont(font)
        self.actionNew_App.setObjectName(_fromUtf8("actionNew_App"))
        self.action_Run = QtGui.QAction(MainWindow)
        self.action_Run.setObjectName(_fromUtf8("action_Run"))
        self.action_Debug = QtGui.QAction(MainWindow)
        self.action_Debug.setObjectName(_fromUtf8("action_Debug"))
        self.action_Stop = QtGui.QAction(MainWindow)
        self.action_Stop.setObjectName(_fromUtf8("action_Stop"))
        self.actionPreference = QtGui.QAction(MainWindow)
        self.actionPreference.setObjectName(_fromUtf8("actionPreference"))
        self.action_Button = QtGui.QAction(MainWindow)
        self.action_Button.setObjectName(_fromUtf8("action_Button"))
        self.action_Save_2 = QtGui.QAction(MainWindow)
        self.action_Save_2.setObjectName(_fromUtf8("action_Save_2"))
        self.actionDialog_Box = QtGui.QAction(MainWindow)
        self.actionDialog_Box.setObjectName(_fromUtf8("actionDialog_Box"))
        self.actionToastAlert = QtGui.QAction(MainWindow)
        self.actionToastAlert.setObjectName(_fromUtf8("actionToastAlert"))
        self.actionProgressSpinner = QtGui.QAction(MainWindow)
        self.actionProgressSpinner.setObjectName(_fromUtf8("actionProgressSpinner"))
        self.actionOrbitting_Dots = QtGui.QAction(MainWindow)
        self.actionOrbitting_Dots.setObjectName(_fromUtf8("actionOrbitting_Dots"))
        self.actionTextInput = QtGui.QAction(MainWindow)
        self.actionTextInput.setObjectName(_fromUtf8("actionTextInput"))
        self.actionOpen_Engine_Group = QtGui.QAction(MainWindow)
        self.actionOpen_Engine_Group.setObjectName(_fromUtf8("actionOpen_Engine_Group"))
        self.actionLua_File_Engine_UI_Elements = QtGui.QAction(MainWindow)
        self.actionLua_File_Engine_UI_Elements.setObjectName(_fromUtf8("actionLua_File_Engine_UI_Elements"))
        self.actionJSON_New_UI_Elements = QtGui.QAction(MainWindow)
        self.actionJSON_New_UI_Elements.setObjectName(_fromUtf8("actionJSON_New_UI_Elements"))
        self.actionNew_Layer = QtGui.QAction(MainWindow)
        self.actionNew_Layer.setObjectName(_fromUtf8("actionNew_Layer"))
        self.actionNew_Project = QtGui.QAction(MainWindow)
        self.actionNew_Project.setObjectName(_fromUtf8("actionNew_Project"))
        self.actionOpen_Project = QtGui.QAction(MainWindow)
        self.actionOpen_Project.setObjectName(_fromUtf8("actionOpen_Project"))
        self.actionSave_Project = QtGui.QAction(MainWindow)
        self.actionSave_Project.setObjectName(_fromUtf8("actionSave_Project"))
        self.actionSlider = QtGui.QAction(MainWindow)
        self.actionSlider.setObjectName(_fromUtf8("actionSlider"))
        self.actionLayoutManager = QtGui.QAction(MainWindow)
        self.actionLayoutManager.setObjectName(_fromUtf8("actionLayoutManager"))
        self.actionScrollPane = QtGui.QAction(MainWindow)
        self.actionScrollPane.setObjectName(_fromUtf8("actionScrollPane"))
        self.actionTabBar = QtGui.QAction(MainWindow)
        self.actionTabBar.setObjectName(_fromUtf8("actionTabBar"))
        self.actionArrowPane = QtGui.QAction(MainWindow)
        self.actionArrowPane.setObjectName(_fromUtf8("actionArrowPane"))
        self.actionButtonPicker = QtGui.QAction(MainWindow)
        self.actionButtonPicker.setObjectName(_fromUtf8("actionButtonPicker"))
        self.actionMenuButton = QtGui.QAction(MainWindow)
        self.actionMenuButton.setObjectName(_fromUtf8("actionMenuButton"))
        self.actionWidgetText = QtGui.QAction(MainWindow)
        self.actionWidgetText.setObjectName(_fromUtf8("actionWidgetText"))
        self.actionWidgetImage = QtGui.QAction(MainWindow)
        self.actionWidgetImage.setObjectName(_fromUtf8("actionWidgetImage"))
        self.actionWidgetRectangle = QtGui.QAction(MainWindow)
        self.actionWidgetRectangle.setObjectName(_fromUtf8("actionWidgetRectangle"))
        self.actionWidgetGroup = QtGui.QAction(MainWindow)
        self.actionWidgetGroup.setObjectName(_fromUtf8("actionWidgetGroup"))
        self.actionWidgetClone = QtGui.QAction(MainWindow)
        self.actionWidgetClone.setObjectName(_fromUtf8("actionWidgetClone"))
        self.actionUngroup = QtGui.QAction(MainWindow)
        self.actionUngroup.setObjectName(_fromUtf8("actionUngroup"))
        self.actionDelete = QtGui.QAction(MainWindow)
        self.actionDelete.setObjectName(_fromUtf8("actionDelete"))
        self.actionClone = QtGui.QAction(MainWindow)
        self.actionClone.setObjectName(_fromUtf8("actionClone"))
        self.actionGroup = QtGui.QAction(MainWindow)
        self.actionGroup.setObjectName(_fromUtf8("actionGroup"))
        self.actionDuplicate = QtGui.QAction(MainWindow)
        self.actionDuplicate.setObjectName(_fromUtf8("actionDuplicate"))
        self.actionLeft = QtGui.QAction(MainWindow)
        self.actionLeft.setObjectName(_fromUtf8("actionLeft"))
        self.action_left = QtGui.QAction(MainWindow)
        self.action_left.setObjectName(_fromUtf8("action_left"))
        self.action_right = QtGui.QAction(MainWindow)
        self.action_right.setObjectName(_fromUtf8("action_right"))
        self.action_top = QtGui.QAction(MainWindow)
        self.action_top.setObjectName(_fromUtf8("action_top"))
        self.action_bottom = QtGui.QAction(MainWindow)
        self.action_bottom.setObjectName(_fromUtf8("action_bottom"))
        self.action_horizontalCenter = QtGui.QAction(MainWindow)
        self.action_horizontalCenter.setObjectName(_fromUtf8("action_horizontalCenter"))
        self.action_verticalCenter = QtGui.QAction(MainWindow)
        self.action_verticalCenter.setObjectName(_fromUtf8("action_verticalCenter"))
        self.action_distributeHorizontally = QtGui.QAction(MainWindow)
        self.action_distributeHorizontally.setObjectName(_fromUtf8("action_distributeHorizontally"))
        self.action_distributeVertically = QtGui.QAction(MainWindow)
        self.action_distributeVertically.setObjectName(_fromUtf8("action_distributeVertically"))
        self.action_bring_to_front = QtGui.QAction(MainWindow)
        self.action_bring_to_front.setObjectName(_fromUtf8("action_bring_to_front"))
        self.action_bring_to_forward = QtGui.QAction(MainWindow)
        self.action_bring_to_forward.setObjectName(_fromUtf8("action_bring_to_forward"))
        self.action_send_to_back = QtGui.QAction(MainWindow)
        self.action_send_to_back.setObjectName(_fromUtf8("action_send_to_back"))
        self.action_send_backward = QtGui.QAction(MainWindow)
        self.action_send_backward.setObjectName(_fromUtf8("action_send_backward"))
        self.actionToggleButton = QtGui.QAction(MainWindow)
        self.actionToggleButton.setObjectName(_fromUtf8("actionToggleButton"))
        self.actionAdd_Horizontal_Guide = QtGui.QAction(MainWindow)
        self.actionAdd_Horizontal_Guide.setObjectName(_fromUtf8("actionAdd_Horizontal_Guide"))
        self.actionAdd_Vertical_Guide = QtGui.QAction(MainWindow)
        self.actionAdd_Vertical_Guide.setObjectName(_fromUtf8("actionAdd_Vertical_Guide"))
        self.actionShow_Guides = QtGui.QAction(MainWindow)
        self.actionShow_Guides.setCheckable(True)
        self.actionShow_Guides.setChecked(True)
        self.actionShow_Guides.setEnabled(True)
        self.actionShow_Guides.setObjectName(_fromUtf8("actionShow_Guides"))
        self.actionSnap_to_Guides = QtGui.QAction(MainWindow)
        self.actionSnap_to_Guides.setCheckable(True)
        self.actionSnap_to_Guides.setChecked(True)
        self.actionSnap_to_Guides.setObjectName(_fromUtf8("actionSnap_to_Guides"))
        self.actionImage = QtGui.QAction(MainWindow)
        self.actionImage.setObjectName(_fromUtf8("actionImage"))
        self.actionSmall_Grid = QtGui.QAction(MainWindow)
        self.actionSmall_Grid.setObjectName(_fromUtf8("actionSmall_Grid"))
        self.actionMedium_Grid = QtGui.QAction(MainWindow)
        self.actionMedium_Grid.setObjectName(_fromUtf8("actionMedium_Grid"))
        self.actionLarge_Grid = QtGui.QAction(MainWindow)
        self.actionLarge_Grid.setObjectName(_fromUtf8("actionLarge_Grid"))
        self.actionWhite = QtGui.QAction(MainWindow)
        self.actionWhite.setObjectName(_fromUtf8("actionWhite"))
        self.actionBlack = QtGui.QAction(MainWindow)
        self.actionBlack.setObjectName(_fromUtf8("actionBlack"))
        self.actionProgressBar = QtGui.QAction(MainWindow)
        self.actionProgressBar.setObjectName(_fromUtf8("actionProgressBar"))
        self.actionRadioButton = QtGui.QAction(MainWindow)
        self.actionRadioButton.setObjectName(_fromUtf8("actionRadioButton"))
        self.actionCheckBox = QtGui.QAction(MainWindow)
        self.actionCheckBox.setObjectName(_fromUtf8("actionCheckBox"))
        self.actionImport_Assets = QtGui.QAction(MainWindow)
        self.actionImport_Assets.setObjectName(_fromUtf8("actionImport_Assets"))
        self.action_Reoptimize = QtGui.QAction(MainWindow)
        self.action_Reoptimize.setObjectName(_fromUtf8("action_Reoptimize"))
        self.actionImport_Skins = QtGui.QAction(MainWindow)
        self.actionImport_Skins.setObjectName(_fromUtf8("actionImport_Skins"))
        self.action_Debugger = QtGui.QAction(MainWindow)
        self.action_Debugger.setObjectName(_fromUtf8("action_Debugger"))
        self.action_CodeEditor = QtGui.QAction(MainWindow)
        self.action_CodeEditor.setObjectName(_fromUtf8("action_CodeEditor"))
        self.actionEditor = QtGui.QAction(MainWindow)
        self.actionEditor.setCheckable(True)
        self.actionEditor.setChecked(True)
        self.actionEditor.setObjectName(_fromUtf8("actionEditor"))
        self.actionInspector = QtGui.QAction(MainWindow)
        self.actionInspector.setCheckable(True)
        self.actionInspector.setChecked(True)
        self.actionInspector.setObjectName(_fromUtf8("actionInspector"))
        self.actionImages = QtGui.QAction(MainWindow)
        self.actionImages.setCheckable(True)
        self.actionImages.setChecked(True)
        self.actionImages.setObjectName(_fromUtf8("actionImages"))
        self.menuFile.addAction(self.actionNew_Project)
        self.menuFile.addAction(self.actionOpen_Project)
        self.menuFile.addAction(self.actionSave_Project)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionNew_Layer)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionImport_Assets)
        self.menuFile.addAction(self.actionImport_Skins)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_CodeEditor)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Exit)
        self.menuView.addAction(self.actionEditor)
        self.menuView.addAction(self.actionInspector)
        self.menuView.addAction(self.actionImages)
        self.menuInsert_UI_Element.addAction(self.actionArrowPane)
        self.menuInsert_UI_Element.addAction(self.action_Button)
        self.menuInsert_UI_Element.addAction(self.actionButtonPicker)
        self.menuInsert_UI_Element.addAction(self.actionCheckBox)
        self.menuInsert_UI_Element.addAction(self.actionDialog_Box)
        self.menuInsert_UI_Element.addAction(self.actionLayoutManager)
        self.menuInsert_UI_Element.addAction(self.actionMenuButton)
        self.menuInsert_UI_Element.addAction(self.actionOrbitting_Dots)
        self.menuInsert_UI_Element.addAction(self.actionProgressBar)
        self.menuInsert_UI_Element.addAction(self.actionProgressSpinner)
        self.menuInsert_UI_Element.addAction(self.actionRadioButton)
        self.menuInsert_UI_Element.addAction(self.actionWidgetRectangle)
        self.menuInsert_UI_Element.addAction(self.actionScrollPane)
        self.menuInsert_UI_Element.addAction(self.actionSlider)
        self.menuInsert_UI_Element.addAction(self.actionTabBar)
        self.menuInsert_UI_Element.addAction(self.actionWidgetText)
        self.menuInsert_UI_Element.addAction(self.actionTextInput)
        self.menuInsert_UI_Element.addAction(self.actionToastAlert)
        self.menuEdit.addAction(self.menuInsert_UI_Element.menuAction())
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionDelete)
        self.menuEdit.addAction(self.actionDuplicate)
        self.menuEdit.addAction(self.actionClone)
        self.menuEdit.addAction(self.actionGroup)
        self.menuEdit.addAction(self.actionUngroup)
        self.menu_align.addAction(self.action_left)
        self.menu_align.addAction(self.action_right)
        self.menu_align.addAction(self.action_top)
        self.menu_align.addAction(self.action_bottom)
        self.menu_align.addAction(self.action_horizontalCenter)
        self.menu_align.addAction(self.action_verticalCenter)
        self.menu_distribute.addAction(self.action_distributeHorizontally)
        self.menu_distribute.addAction(self.action_distributeVertically)
        self.menu_arrange.addAction(self.action_bring_to_front)
        self.menu_arrange.addAction(self.action_bring_to_forward)
        self.menu_arrange.addAction(self.action_send_to_back)
        self.menu_arrange.addAction(self.action_send_backward)
        self.menuArrange.addAction(self.menu_align.menuAction())
        self.menuArrange.addAction(self.menu_distribute.menuAction())
        self.menuArrange.addAction(self.menu_arrange.menuAction())
        self.menuBackground.addAction(self.actionImage)
        self.menuBackground.addAction(self.actionSmall_Grid)
        self.menuBackground.addAction(self.actionMedium_Grid)
        self.menuBackground.addAction(self.actionLarge_Grid)
        self.menuBackground.addAction(self.actionWhite)
        self.menuBackground.addAction(self.actionBlack)
        self.menuView_2.addAction(self.menuBackground.menuAction())
        self.menuView_2.addSeparator()
        self.menuView_2.addAction(self.actionAdd_Horizontal_Guide)
        self.menuView_2.addAction(self.actionAdd_Vertical_Guide)
        self.menuView_2.addSeparator()
        self.menuView_2.addAction(self.actionShow_Guides)
        self.menuView_2.addAction(self.actionSnap_to_Guides)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuArrange.menuAction())
        self.menubar.addAction(self.menuView_2.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "TrickPlay Visual Editor ", None))
        MainWindow.setProperty("aaa", _translate("MainWindow", "sdfsf", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuView.setTitle(_translate("MainWindow", "Windows", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.menuInsert_UI_Element.setTitle(_translate("MainWindow", "Insert UI Element", None))
        self.menuArrange.setTitle(_translate("MainWindow", "Arrange", None))
        self.menu_align.setTitle(_translate("MainWindow", "Align", None))
        self.menu_distribute.setTitle(_translate("MainWindow", "Distribute", None))
        self.menu_arrange.setTitle(_translate("MainWindow", "Arrange", None))
        self.menuView_2.setTitle(_translate("MainWindow", "View", None))
        self.menuBackground.setTitle(_translate("MainWindow", "Background", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.action_Exit.setText(_translate("MainWindow", "Exit", None))
        self.action_Exit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.action_Save.setText(_translate("MainWindow", "Save file", None))
        self.action_Save.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.action_New.setText(_translate("MainWindow", "Create new  app...", None))
        self.action_New.setShortcut(_translate("MainWindow", "Ctrl+Shift+N", None))
        self.action_Cut.setText(_translate("MainWindow", "Cut", None))
        self.action_Cut.setShortcut(_translate("MainWindow", "Ctrl+X", None))
        self.action_Copy.setText(_translate("MainWindow", "Copy", None))
        self.action_Copy.setShortcut(_translate("MainWindow", "Ctrl+C", None))
        self.action_Paste.setText(_translate("MainWindow", "Paste", None))
        self.action_Paste.setShortcut(_translate("MainWindow", "Ctrl+V", None))
        self.action_Delete.setText(_translate("MainWindow", "Delete", None))
        self.actionSelect_All.setText(_translate("MainWindow", "Select all", None))
        self.actionSelect_All.setShortcut(_translate("MainWindow", "Ctrl+A", None))
        self.action_Close.setText(_translate("MainWindow", "Close file", None))
        self.action_Close.setShortcut(_translate("MainWindow", "Ctrl+W", None))
        self.action_Save_As.setText(_translate("MainWindow", "Save file as...", None))
        self.actionUndo.setText(_translate("MainWindow", "Undo", None))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Z", None))
        self.actionRedo.setText(_translate("MainWindow", "Redo", None))
        self.actionRedo.setShortcut(_translate("MainWindow", "Ctrl+R", None))
        self.actionDebug.setText(_translate("MainWindow", "Debug", None))
        self.actionRun.setText(_translate("MainWindow", "Run", None))
        self.actionStep_into.setText(_translate("MainWindow", "Step Into", None))
        self.actionStep_into.setShortcut(_translate("MainWindow", "Ctrl+I", None))
        self.actionStep_over.setText(_translate("MainWindow", "Step over", None))
        self.actionStep_over.setShortcut(_translate("MainWindow", "Ctrl+K", None))
        self.actionDebug_View.setText(_translate("MainWindow", "Debug View", None))
        self.actionRun_View.setText(_translate("MainWindow", "Run View", None))
        self.actionSave_All.setText(_translate("MainWindow", "Save all files", None))
        self.actionSearch.setText(_translate("MainWindow", "Search...", None))
        self.actionSearch.setShortcut(_translate("MainWindow", "Ctrl+F", None))
        self.actionSearch_Replace.setText(_translate("MainWindow", "Find/Replace...", None))
        self.actionSearch_Replace.setShortcut(_translate("MainWindow", "Ctrl+F", None))
        self.actionGo_to_line.setText(_translate("MainWindow", "Go to line...", None))
        self.actionGo_to_line.setShortcut(_translate("MainWindow", "Ctrl+J", None))
        self.actionSearch_in_Files.setText(_translate("MainWindow", "Search in Files...", None))
        self.actionBeutify_Selection.setText(_translate("MainWindow", "Beutify Selection", None))
        self.actionStrip_Whitespace.setText(_translate("MainWindow", "Strip Whitespace", None))
        self.actionStep_out.setText(_translate("MainWindow", "Step out", None))
        self.actionStep_out.setShortcut(_translate("MainWindow", "Ctrl+M", None))
        self.actionStop.setText(_translate("MainWindow", "Stop", None))
        self.actionPause.setText(_translate("MainWindow", "Pause", None))
        self.actionPause.setShortcut(_translate("MainWindow", "Ctrl+P", None))
        self.actionContinue.setText(_translate("MainWindow", "Continue", None))
        self.actionContinue.setShortcut(_translate("MainWindow", "Ctrl+B", None))
        self.actionNew_File.setText(_translate("MainWindow", "Create new file...", None))
        self.actionNew_File.setShortcut(_translate("MainWindow", "Ctrl+N", None))
        self.actionNew_Folder.setText(_translate("MainWindow", "New Folder", None))
        self.actionOpen_App.setText(_translate("MainWindow", "Open existing app...", None))
        self.actionOpen_App.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionNew_App.setText(_translate("MainWindow", "New App", None))
        self.action_Run.setText(_translate("MainWindow", "Run", None))
        self.action_Run.setShortcut(_translate("MainWindow", "Ctrl+F11", None))
        self.action_Debug.setText(_translate("MainWindow", "Debug", None))
        self.action_Debug.setShortcut(_translate("MainWindow", "F11", None))
        self.action_Stop.setText(_translate("MainWindow", "Stop", None))
        self.action_Stop.setShortcut(_translate("MainWindow", "Esc", None))
        self.actionPreference.setText(_translate("MainWindow", "Preference...", None))
        self.action_Button.setText(_translate("MainWindow", "Button", None))
        self.action_Save_2.setText(_translate("MainWindow", "Save", None))
        self.actionDialog_Box.setText(_translate("MainWindow", "Dialog Box", None))
        self.actionToastAlert.setText(_translate("MainWindow", "ToastAlert", None))
        self.actionProgressSpinner.setText(_translate("MainWindow", "ProgressSpinner", None))
        self.actionOrbitting_Dots.setText(_translate("MainWindow", "Orbitting Dots", None))
        self.actionTextInput.setText(_translate("MainWindow", "TextInput", None))
        self.actionOpen_Engine_Group.setText(_translate("MainWindow", "Open Engine Group", None))
        self.actionLua_File_Engine_UI_Elements.setText(_translate("MainWindow", "Lua File (Engine UI Elements)", None))
        self.actionJSON_New_UI_Elements.setText(_translate("MainWindow", "JSON (New UI Elements)", None))
        self.actionNew_Layer.setText(_translate("MainWindow", "New Layer", None))
        self.actionNew_Project.setText(_translate("MainWindow", "New Project...", None))
        self.actionOpen_Project.setText(_translate("MainWindow", "Open Project...", None))
        self.actionSave_Project.setText(_translate("MainWindow", "Save Project", None))
        self.actionSlider.setText(_translate("MainWindow", "Slider", None))
        self.actionLayoutManager.setText(_translate("MainWindow", "LayoutManager", None))
        self.actionScrollPane.setText(_translate("MainWindow", "ScrollPane", None))
        self.actionTabBar.setText(_translate("MainWindow", "TabBar", None))
        self.actionArrowPane.setText(_translate("MainWindow", "ArrowPane", None))
        self.actionButtonPicker.setText(_translate("MainWindow", "ButtonPicker", None))
        self.actionMenuButton.setText(_translate("MainWindow", "MenuButton", None))
        self.actionWidgetText.setText(_translate("MainWindow", "Text", None))
        self.actionWidgetImage.setText(_translate("MainWindow", "WidgetImage", None))
        self.actionWidgetRectangle.setText(_translate("MainWindow", "Rectangle", None))
        self.actionWidgetGroup.setText(_translate("MainWindow", "WidgetGroup", None))
        self.actionWidgetClone.setText(_translate("MainWindow", "WidgetClone", None))
        self.actionUngroup.setText(_translate("MainWindow", "Ungroup", None))
        self.actionDelete.setText(_translate("MainWindow", "Delete", None))
        self.actionClone.setText(_translate("MainWindow", "Clone", None))
        self.actionGroup.setText(_translate("MainWindow", "Group", None))
        self.actionDuplicate.setText(_translate("MainWindow", "Duplicate", None))
        self.actionLeft.setText(_translate("MainWindow", "Left", None))
        self.action_left.setText(_translate("MainWindow", "Left", None))
        self.action_right.setText(_translate("MainWindow", "Right", None))
        self.action_top.setText(_translate("MainWindow", "Top", None))
        self.action_bottom.setText(_translate("MainWindow", "Bottom", None))
        self.action_horizontalCenter.setText(_translate("MainWindow", "Horizontal Center", None))
        self.action_verticalCenter.setText(_translate("MainWindow", "Vertical Center", None))
        self.action_distributeHorizontally.setText(_translate("MainWindow", "Horizontally", None))
        self.action_distributeVertically.setText(_translate("MainWindow", "Vertically", None))
        self.action_bring_to_front.setText(_translate("MainWindow", "Bring to Front", None))
        self.action_bring_to_forward.setText(_translate("MainWindow", "Bring to Forward", None))
        self.action_send_to_back.setText(_translate("MainWindow", "Send to Back", None))
        self.action_send_backward.setText(_translate("MainWindow", "Send Backward", None))
        self.actionToggleButton.setText(_translate("MainWindow", "ToggleButton", None))
        self.actionAdd_Horizontal_Guide.setText(_translate("MainWindow", "Add Horizontal Guide", None))
        self.actionAdd_Vertical_Guide.setText(_translate("MainWindow", "Add Vertical Guide", None))
        self.actionShow_Guides.setText(_translate("MainWindow", "Show Guides", None))
        self.actionSnap_to_Guides.setText(_translate("MainWindow", "Snap to Guides", None))
        self.actionImage.setText(_translate("MainWindow", "Image...", None))
        self.actionSmall_Grid.setText(_translate("MainWindow", "Small Grid", None))
        self.actionMedium_Grid.setText(_translate("MainWindow", "Medium Grid", None))
        self.actionLarge_Grid.setText(_translate("MainWindow", "Large Grid", None))
        self.actionWhite.setText(_translate("MainWindow", "White", None))
        self.actionBlack.setText(_translate("MainWindow", "Black", None))
        self.actionProgressBar.setText(_translate("MainWindow", "ProgressBar", None))
        self.actionRadioButton.setText(_translate("MainWindow", "RadioButton", None))
        self.actionCheckBox.setText(_translate("MainWindow", "CheckBox", None))
        self.actionImport_Assets.setText(_translate("MainWindow", "Import Assets...", None))
        self.action_Reoptimize.setText(_translate("MainWindow", "Reoptimize", None))
        self.actionImport_Skins.setText(_translate("MainWindow", "Import Skins...", None))
        self.action_Debugger.setText(_translate("MainWindow", "Debug", None))
        self.action_CodeEditor.setText(_translate("MainWindow", "Code Editor...", None))
        self.actionEditor.setText(_translate("MainWindow", "Editor", None))
        self.actionInspector.setText(_translate("MainWindow", "Inspector", None))
        self.actionImages.setText(_translate("MainWindow", "Images", None))

