=head1 NAME

trickplay -  run the trickplay-sdk emulator

=head1 SYNOPSIS

trickplay [app]

=head1 DESCRIPTION

This command runs the TrickPlay SDK emulator. You can pass
the path to an app bundle as the only parameter.

=head1 EXAMPLES

Run my-app in your home directory:

          trickplay /home/me/my-app

=head1 EXIT STATUS

trickplay returns a zero exit status if it succeeds. Non
zero is returned in case of failure.

=head1 AUTHOR

Pablo Pissanetzky <pablo@trickplay.com>




