# - Find cairo
# Find the native Cairo headers and libraries.
#

# Look for the header file.
FIND_PATH(CAIRO_INCLUDE_DIR NAMES cairo/cairo.h)
MARK_AS_ADVANCED(CAIRO_INCLUDE_DIR)

# Look for the library.
FIND_LIBRARY(CAIRO_LIBRARY NAMES cairo)
MARK_AS_ADVANCED(CAIRO_LIBRARY)

# handle the QUIETLY and REQUIRED arguments and set CAIRO_FOUND to TRUE if 
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CAIRO DEFAULT_MSG CAIRO_LIBRARY CAIRO_INCLUDE_DIR)

IF(CAIRO_FOUND)
  SET(CAIRO_LIBRARIES ${CAIRO_LIBRARY})
  SET(CAIRO_INCLUDE_DIRS ${CAIRO_INCLUDE_DIR}/cairo)
ELSE(CAIRO_FOUND)
  SET(CAIRO_LIBRARIES)
  SET(CAIRO_INCLUDE_DIRS)
ENDIF(CAIRO_FOUND)
