return {
{"How many countries border San Marino?",1,2,3,4,"Geography",1},
{"With how many countries does the US share a land border?",2,3,4,1,"Geography",1},
{"How many faces has the clock on Big Ben's tower?",4,2,3,1,"Geography",1},
{"How many hours behind Greenwich Mean Time is California?",8,6,10,12,"Geography",1},
{"How many fountains are found in the gardens at the Palace of Versailles? ","1,400","140 ",14,"14,000","Geography",1},
{"How many candles were used to light the Hall of Mirrors in the Palace of Versailles?    ","3,000",300,"33,000","333,000","Geography",1},
{"On a clear day how far can one see from the observation platform of the Empire State Building?","130 km","3 km","30 km","630  km","Geography",1},
{"Peter Minuit of the Dutch West India Company bought Manhattan island from the local indians in 1626 with cloth, trinkets and beads worth the equivalent  of what?","24 dollars","24 cents","240 dollars","2,400 dollars","Geography",1},
{"In which European city is Schiphol airport?","Amsterdam","Budapest","Warsaw","Athens","Geography",1},
{"Where is Dam Square?","Amsterdam","Berlin","Copenhagen","Darmstadt","Geography",1},
{"In which city can one visit the Palace of the Popes?","Avignon","Rome","Nancy","Madrid","Geography",1},
{"The jade green waters of Lake Louise are found in which national park?","Banff, Canada","Kruger, South Africa","Serengeti, Tanzania","Yellowstone, USA","Geography",1},
{"In which county can one find Luton Airport?","Bedfordshire","Hertfordshire","Kent","Essex","Geography",1},
{"With 196 tonnes, the heaviest what ever built is found within the walls of the Kremlin?","bell","gold bar","cannon ball","statue","Geography",1},
{"Since 1981, Mumbai is the official name for which Indian city?","Bombay","Calcutta","Delhi","Bangalore","Geography",1},
{"The name of which capital city is the Latin word for a red dye wood?","Brasilia","Vienna","Berlin","Rome","Geography",1},
{"Where in London can one view the Magna Carta and the Rosetta Stone?","British Museum","Tate Gallery","National Gallery","Tower of London","Geography",1},
{"With 40 tonnes, the largest what ever built is found within the walls of the Kremlin?","cannon","crucifix","chandelier","chalice","Geography",1},
{"Where is the Astronaut Hall of Fame located?","Cape Canaveral","Washington","Houston","New York","Geography",1},
{"In which city can one board the luxurious 'Blue Train'?","Cape Town","Edinburgh","Vancouver","Istanbul","Geography",1},
{"In which city does the National Assembly of Wales sit?","Cardiff","Newport","Swansea","St. Davids","Geography",1},
{"Which London street does one associate with the 1960s fashion scene?","Carnaby","Fleet","Threadneedle","Pall Mall","Geography",1},
{"In which city is the world famous Sears Tower skyscraper located?","Chicago","New York","Boston","Detroit","Geography",1},
{"How many litres of beer are consumed each year at the Oktoberfest in Munich?","circa 6,000,000"," circa 60,000,000","circa 600,000","circa 60,000","Geography",1},
{"Which metal was used to construct the outside hull of the Statue of Liberty?","copper","brass","silver","iron","Geography",1},
{"In which city is the world famous Burg Al Arab skyscraper located?","Dubai","Cairo","Tehran","Kuwait City","Geography",1},
{"Which language is Afrikaans derived from?","Dutch","German","Spanish","English","Geography",1},
{"The Royal Mile is a famous street in which capital city?","Edinburgh","Ottawa","London","Dublin","Geography",1},
{"Which European capital has the nickname 'The Athens of the north'?","Edinburgh","Paris","Berlin","Helsinki","Geography",1},
{"Famine in which country triggered the Band Aid Charity?","Ethiopia","Sudan","South Africa","Zimbabwe","Geography",1},
{"Which country's postage stamps bear the inscription \"Suomi\"?","Finland","Sweden","Denmark","Norway","Geography",1},
{"The Uffizien museum, a feast for the eyes for lovers of Renaissance paintings, is located in which city?","Florence","Rome","Vatican City","Milan","Geography",1},
{"Whose upper house of Parliament is called the Bundesrat?","Germany's","Belgium's","France's","Spain's","Geography",1},
{"What is the name of the film prize awarded each year at the Venice film festival?","Golden Lion","Golden Bear","Golden Eagle","Golden Star","Geography",1},
{"In which country is the harbour city Mumbai?","India","China","Senegal","Japan","Geography",1},
{"In which city is the world famous skyscraper Petronas Towers located?","Kuala Lumpur","Shanghai","New York","Dubai","Geography",1},
{"It is said that the residents of which European capital never sleep?","Madrid","Oslo","Warsaw","Dublin","Geography",1},
{"In which city is the famous Prado museum?","Madrid","St Petersburg","Florence","Vatican","Geography",1},
{"Which destination for 60s hippies has been called the Paris of the Sahara?  ","Marrakesh","Tripolis","Cairo","Luxor","Geography",1},
{"The German city of Lübeck is world famous for which product?","marzipan","pickled herring","sauerkraut","Frankfurters","Geography",1},
{"GUM is the world famous dept store in which city?","Moscow","New York","Paris","Tokyo","Geography",1},
{"Which famous castle was the inspiration for the Disney theme park castle?","Neuschwanstein Castle","Edinburgh Castle","Windsor Castle","Mount Saint Michel Castle","Geography",1},
{"In which city is the world famous Chrysler Building skyscraper located?","New York","Chicago","San Francisco ","Detroit","Geography",1},
{"In which city is the world famous Woolworth Building skyscraper located?","New York","London","Chicago","Boston","Geography",1},
{"In which country can one find the Giant's Causeway?","Northern Ireland","Scotland","France","Canada","Geography",1},
{"The famous 'Lake Palace' in India, once a summer residence for royalty and now a luxury hotel, was the setting  for which action film? ","Octopussy","Star Wars. The Empire Strikes Back","Mission Impossible II","Crouching Tiger, Hidden Dragon","Geography",1},
{"In which capital city is the Roland Garos stadium?","Paris","Prague","Madrid","Budapest","Geography",1},
{"The victory goddess Victoria and her chariot on the top of the Brandenburger Gate in Berlin spent the years between 1806 and 1814 in which capital city?","Paris","London","Moscow","Rome","Geography",1},
{"The Emperors Palace or Forbidden City is located in which city?","Peking","Shanghai","Hong Kong","Xi'an","Geography",1},
{"The Cathedral of our Lady in Antwerp contains four masterpieces depicting Biblical scenes by which famous Baroque painter?","Peter Paul Rubens","Vincent van Gogh","Raffael","Rembrandt","Geography",1},
{"The 'Liberty Bell' is found in which US city?","Philadelphia","Washington","New York","Boston","Geography",1},
{"In which harbour city is Lord Nelson's flagship HMS Victory?","Portsmouth","Plymouth","Bristol","Liverpool","Geography",1},
{"The longest bridge built in the middleages in Europe, the Charles Bridge, is located in which capital city?","Prague","London","Paris","Oslo","Geography",1},
{"What creature appears on the Welsh national flag?","Red dragon","Yellow dafffodil","Green leek","White sheep","Geography",1},
{"Which city has the nickname 'Venice of the north'?","St Petersburg","Montreal","Glasgow","Helsinki","Geography",1},
{"Which famous city, sometimes called the Venice of the north, was built on 12 islands?","St Petersburg","Glasgow","Ottawa","Oslo","Geography",1},
{"What is the name of the famous mountain that overlooks Cape Town, South Africa?","Table","Plate","Chalice","Divan","Geography",1},
{"In which famous buiding did Catherine the Great keep her private art collection?","The Eremitage","The Kremlin","The Summer Palace","The Bolshoi Theatre","Geography",1},
{"Niagara Falls Canada, where the awe inspiring Horseshoe Falls is located, has been given which nickname?    ","The Honeymoon City","The Misty City","The Windy City","The City of Lights","Geography",1},
{"Which golf course is called 'the home of golf'?","The Royal and Ancient Golf Club St Andrews","Gleneagles","Pebble Beach","Sunningdale","Geography",1},
{"Hadrian's Wall was built in order to keep which wild men out of the Roman Empire?","The Scots","The Welsh","The Vikings","The Mongols","Geography",1},
{"The Potala Palace was once the winter residence for which man? ","The Dalai Lama","Pu  Li","Kubla Khan","El Cid","Geography",1},
{"In which city is the CN Tower, the tallest free standing structure in the world?","Toronto","Chicago","Hong Kong","Moscow","Geography",1},
{"The 'Book of Kells', a 1,300 year old masterpiece of western calligraphy, is found in which university?","Trinity College, Dublin"," Oxford","Cambridge","Sorbonne, Paris  ","Geography",1},
{"Angel Falls, the worlds highest waterfall is located in which country?","Venezuela","Zambia","Canada","Switzerland","Geography",1},
{" In which city is the famous Bridge of Sighs?","Venice","Paris","Rome","Prague","Geography",1},
{"Which Canadian provincial capital is nicknamed 'Little England'?","Victoria","Toronto","Quebec City","Halifax","Geography",1},
{"The Taj Mahal was constructed with which material?","White Marble","White Granite","White Ivory","White Opals","Geography",1},
{"In which US national park is the geysir named 'Old Faithful' located?","Yellowstone","Banff","Grand Teton","Bryce Canyon","Geography",1},
{"How many bridges are there over the firth of fourth?",2,3,4,1,"Geography",2},
{"How many American states begin and end with the letter 'A'?",3,4,5,2,"Geography",2},
{"How many time zones are there in the USA?",4,5,2,1,"Geography",2},
{"What is the unlucky number in China?",4,13,7,33,"Geography",2},
{"How many stories high is the Empire State building?",102,62,162,202,"Geography",2},
{"What is the population of the Czech Rep?","10.3 million","4.5 million","57.6 million","80.2 million","Geography",2},
{"Angel Falls, the highest waterfall in the world is how many times higher than the Niagara Falls?","15X","5X","2X","25X","Geography",2},
{"How much does the Petersglocke, the worlds heaviest church bell in the Cologne Cathedral weigh ?","24 tonnes","4 tonnes","240 tonnes","124 tonnes","Geography",2},
{"To the nearest million, what was the population of Wales in 2001?","3 million","1 million","5 million","10 million","Geography",2},
{"What is the cozy interior temperature in the world famous Ice Hotel in Jukkasjärvi Sweden?","-5° C to -8°C","-13°C to -16°C","0°C to -3°C","-27°C to -30°C","Geography",2},
{"What is the population of Iran?","71.4 million","3.8 million","33.5 million","144.5 million","Geography",2},
{"What is the population of Vietnam?","78.8 million","10.1 million","39.9 million","123.3 million","Geography",2},
{"Lake Assal is the lowest point on which continent?","Africa","Asia","Australia","Antarctic","Geography",2},
{"Where do the largest vegetables in the US grow?","Alaska","Hawaii","Florida","New Mexico","Geography",2},
{"What is the name of the famous ancient temple city in the jungle of Cambodia?","Angkor Wat","Penang","Amanwana","Yogyakarta","Geography",2},
{"The Chrysler Building in New York City is an example of which style of architecture?","Art Deco","Byzantine","Post Modernism","Baroque","Geography",2},
{"The Sagrada Familia Cathedral in Barcelona is an example of which style of architecture?","Art Nouveau","Neo Gothic","Renaissance","Romanesque","Geography",2},
{"Lake Eyre is the lowest point on which continent?","Australia","Europe","North America","Antarctic","Geography",2},
{"The Gibson desert is found in which country?","Australia","South Africa","Canada","USA","Geography",2},
{"Which country does not border Poland?","Austria","Slovakia","Germany","Lithuania","Geography",2},
{"The Palace of Versailles is an example of which style of architecture?","Baroque","Romanesque","Greek","Gothic","Geography",2},
{"St Paul's Cathedral in London is an example of which style of architecture?","Baroque","Art Deco","Gothic","Neo Classical","Geography",2},
{"What is the only breed of dog that is allowed to testify in a US courtroom?","Bloodhound","Poodle","German Shepard","Collie","Geography",2},
{"Until 1763, Salvador de Bahia was the capital of which country?","Brazil","Spain","Mexico","Portugal","Geography",2},
{"The Hagia Sophia in Istanbul is an example of which style of architecture?","Byzantine","Roman","Gothic","Greek","Geography",2},
{"The Bay of Fundy is off the coast of which country?","Canada","Australia","New Zealand","South Africa","Geography",2},
{"The name of which capital city stems from the native word for 'meeting place'?","Canberra, Australia","Paris, France","Ottawa, Canada","Edinburgh, Scotland","Geography",2},
{"What is the name of the 13th century spa city in the Czech Rep. that attracted the likes of Chopin, Beethoven, Bach and King Edward VII?","Carlsbad","Spa","Baden Baden","Bad Gastein","Geography",2},
{"Which country has only one time zone?","China","Canada","Russia","Brazil","Geography",2},
{"Which country has the largest army in the world?","China","North Korea","India","USA","Geography",2},
{"Which contemporary artist wrapped up the Reichstag in Berlin with 100,000 m2 of polypropylene fabric in the summer of 1995?","Christo","Yoko Ono","H.R. Giger","Andy Warhol","Geography",2},
{"When did the construction of the  Pyramids of Giseh first begin?  ","circa 2500 BC"," circa 5500 BC","circa 500 BC","circa 50 BC","Geography",2},
{"The Grand Place or main market square in Brussels hosts the 'flower carpet' festival each August. How many begonias are used?","circa 700,000","circa 7,000,000","circa 70,000","circa 7,000","Geography",2},
{"In which cathedral is the Petersglocke, the worlds largest church bell?","Cologne","St Peters, Vatican City","Canterbury","Durham","Geography",2},
{"Which country does not border Bolivia?","Colombia","Brazil","Peru","Chile","Geography",2},
{"Which country does not border Greece?","Croatia","Turkey","Albania","Bulgaria","Geography",2},
{"Banana is a harbour city in which country?","Dem Rep of Congo","Brazil","Indonesia","Colombia","Geography",2},
{"Mount Elbrus is the highest point on which continent?","Europe","Asia","North America","Antarctic","Geography",2},
{"The world famous Oberammergau passion play in Bayern is held how often?","every 10 years","every year","every 50 years","every 2 years","Geography",2},
{"In which city, famous for its ship building, was the ocean liner QE2  built?","Glasgow","Belfast","Southampton","Portsmouth","Geography",2},
{"South Africa is the world's leading exporter of what?","Gold","Silver","Diamond","Platinum","Geography",2},
{"Which railway station has the most platforms in the world?","Grand Central, New York","Waterloo, London","Frankfurt Main","Gare du Nord, Paris","Geography",2},
{"Which strait seperates the Persian gulf and the gulf of Oman?","Hormuz","Bosporus","Malacca","Dardanelles","Geography",2},
{"What country does not border Afghanistan?","India","Pakistan","China","Uzbekistan","Geography",2},
{"Where would you find the volcano named Krakatoa? ","Indonesia","Malaysia","China","India","Geography",2},
{"Dingle Bay is off the coast of which country?","Ireland","Canada","Australia","New Zealand","Geography",2},
{"Which city in Turkey is located in Europe and in Asia?","Istanbul","Ankara","Dodomar","Pamukulai","Geography",2},
{"Montego Bay is off the coast of which country?","Jamaica","Barbados","Bermuda","Trinidad and Tobago","Geography",2},
{"Where in New York City is the 'Canyon of Heroes', where the famous ticker tape parades take place?","Lower Broadway","Wall Street","Fifth Avenue","Times Square","Geography",2},
{"According to the World Health Organisation which capital city has the worst air pollution?","Mexico City","London","Moscow","Cairo","Geography",2},
{"Who designed the uniform worn by the Vatican City's Swiss Guard?","Michalangelo","Da Vinci","Raffael","Galileo","Geography",2},
{"Which Is The Most Densely Populated Country In Europe?","Monaco","Vatican City","Andorra","Luxembourg","Geography",2},
{"What do the citizens of Brussels love to eat with their frites (French fries)?","mussels","savoury sausage","eel","Brussel sprouts","Geography",2},
{"The Houses Of Parliament in London is an example of which style of architecture?","Neo Gothic","Baroque","Gothic","Art Deco","Geography",2},
{"The Dominion Parliament buildings in Ottawa are an example of which style of architecture?","Neo Gothic","Roman","Renaissance","Art Deco","Geography",2},
{"In which country is the mountain named Annapurna found?","Nepal","Argentina","Russia","Switzerland","Geography",2},
{"In which US state is Area 51?","Nevada","New Mexico","Texas","Arizona","Geography",2},
{"The Bay of Plenty is off the coast of which country?","New Zealand","Australia","Canada","South Africa","Geography",2},
{"In which country is Mt Cook?","New Zealand","Canada","USA","Argentina","Geography",2},
{"Into which body of water does the Rhine river flow?","North Sea","Black sea","Caspian Sea","Baltic Sea","Geography",2},
{"In which country is there a town named 'Hell'?","Norway","Canada","Australia","Ireland","Geography",2},
{"On what river is the capital city of Canada?","Ottawa","Windigo","Winnipeg ","Montreal ","Geography",2},
{"The mysterious Inca city Machu Picchu is found in which country?","Peru","Mexico","Chile","Colombia","Geography",2},
{"Which country does not border Austria?","Poland","Germany","Hungary","Czech Rep","Geography",2},
{"With a capacity for 220,000 spectators, in which capital city is Strahov, the largest stadium in the world?","Prague"," Moscow","Warsaw","Vienna","Geography",2},
{"In which City would you find St. Peter's Basilica?","Rome","Madrid","St. Petersburg","Moscow","Geography",2},
{"Why was the Munich Oktoberfest cancelled in 1923 and 1924?","Runaway inflation","Civil war","Spanish flu","Brewery strike","Geography",2},
{"When motoring west in which city does Route 66 end?","Santa Monica","LA","Oakland","San Francisco","Geography",2},
{"In which city is the world famous Jin Mao skyscraper located?","Shanghai","Hong Kong","Beijing","Taipei","Geography",2},
{"Which metal made the Bolivian city Potosi one of the richest cities in the world in the 17th century?","silver","gold","aluminium","copper","Geography",2},
{"Which country produces the most gold?","South Africa","Australia","Dem Rep Congo","Canada","Geography",2},
{"The Valdes Peninsula is the lowest point on which continent?","South America","Europe","Antarctic","Australia","Geography",2},
{"Mount Aconcagua is the highest point on which continent?","South America","Asia","Antarctic","Australia","Geography",2},
{"In which country is the harbour city Inchon?","South Korea","India","Brazil","Japan","Geography",2},
{"50% of all the men on the Greek island Corfu have which first name?","Spiro","Achilles","Alexis","Stavros","Geography",2},
{"What is the name of the largest star sapphire in the world which is found in New York City's American Museum of Natural History?","Star of India","Star of Africa ","Star of Cairo","Star of Bethleham","Geography",2},
{"Which country does not border Luxembourg?","Switzerland","Germany","France","Belgium","Geography",2},
{"In which country is the mountain named Jungfrau found?","Switzerland","Italy","France","New Zealand  ","Geography",2},
{"Which country does not border South Africa?","Tanzania","Namibia","Swaziland","Lesotho","Geography",2},
{"Younge Street, the longest street in the world, begins in which Canadian city?","Toronto","Montreal","Vancouver","Quebec City","Geography",2},
{"The ruins of ancient Carthage are found in the suburbs of which modern city?","Tunis","Cairo","Tripolis","Beirut","Geography",2},
{"Which African country is not a monarchy?","Tunisia","Morocco","Swaziland","Lesotho","Geography",2},
{"In which country is Mt Ararat?","Turkey","Russia","Nepal","Switzerland","Geography",2},
{"Which country does not border Turkey?","Turkmenistan","Bulgaria","Iran","Iraq","Geography",2},
{"Where does a Halbardier Gaurdsman work?","Vatican","Tower of London","Mt Olympus","Swiss Border","Geography",2},
{"The oldest film festival in the world takes place in which European city?","Venice","Cannes","Berlin","Edinburgh","Geography",2},
{"Which goddess of victory is riding a chariot on the Brandenberger Gate in Berlin?","Victoria","Athena","Nike","Brunhilda","Geography",2},
{"What is Europe's longest river? ","Volga","Danube","Rhine","Rhone","Geography",2},
{"Which countries name stems from the Germanic word for foreign?","Wales","Spain","Germany","Poland","Geography",2},
{"With 1,000 plus rooms, what is the largest inhabited castle in the world?","Windsor Castle","The Alhambra","Warwich Castle","Edinburgh Castle","Geography",2},
{"During a WWII air raid the firemen in Freiburg im Breisgau used what to put out the fire in the historic Kaufhaus after they ran out of water?","wine","schnapps","beer","milk","Geography",2},
{"How many months does the average American spend in a lifetime waiting at a red light?",6,1,12,18,"Geography",3},
{"How many countries lie between Mexico and Colombia?",7,10,3,5,"Geography",3},
{"How many hours a month does the average American spend in a shopping mall?",12,6,24,48,"Geography",3},
{"How many countries border Russia?",14,8,25,19,"Geography",3},
{"How many countries border China?",16,10,26,7,"Geography",3},
{"How many people live on Ellesmere Island, the 10th largest island in the world?",106,"1,106",6,"10,106","Geography",3},
{"How many rooms are there in the White House?",132,32,72,272,"Geography",3},
{"How many lakes are there in Finland?","187,880","8,880","87,880","887,880","Geography",3},
{"According to the UN how many people in the world are starving?","820,000,000","1.5 billion","82,000,000","420,000,000","Geography",3},
{"Most sources claim that Route 66 is how many miles all the way?","2,448 miles","2,848 miles","1,848 miles","3,448 miles","Geography",3},
{"To the nearest thousand square kilometres what is the land area of Wales?","21,000 sq km","5,000 sq km","51,000 sq km","100,100 sq km","Geography",3},
{"What is the population of Saudi Arabia?","22.million","123.3 million","3.2 million","65.2 million","Geography",3},
{"The salt content in the Dead Sea which enables a swimmer to float like a cork is how many times higher than that of the Atlantic ocean?","7X","2X","22X","77x","Geography",3},
{"The Bridge of Sighs in Venice connected  the Doge's Palace with what?","A state prison and place of execution","A tax office","A hospital","A Turkish bath house","Geography",3},
{"Which European city is nicknamed the 'Granite City'?","Aberdeen","The Vatican","Lisbon","Munich","Geography",3},
{"The crown of the Empire State building was originally built for which purpose?","airship dock","firemans lookout","flag pole","weather station","Geography",3},
{"The Vinson Massive is the highest point on which continent?","Antarctic","Europe","Australia","South America","Geography",3},
{"In which country is the mountain named Aconcagua found?","Argentina","Mexico","Nepal","Switzerland","Geography",3},
{"Which country produces the most opals?","Australia","India","USA","Russia","Geography",3},
{"Mount Kosciusko is the highest point on which continent?","Australia","Europe","Antarctic","Africa","Geography",3},
{"Red, as in Red Square, was the old Slavic synonym for what?","beauty","power","wealth","death","Geography",3},
{"Into which body of water does the Danube river flow?","Black Sea","North Sea","Baltic Sea","Caspian Sea","Geography",3},
{"Which country does not have a bird on its flag?","Brazil","Mexico","Eygpt","Dominican Rep","Geography",3},
{"In which county is chequers, the prime ministers country residence?","Buckinghamshire","Surrey","Middlesex","Oxfordshire","Geography",3},
{"Lake Tahoe is on the border of Nevada and which other US state?","California","Arizona","Oregon","Utah","Geography",3},
{"The Gothic Chartes Cathedral in France has famous stained glass windows which produce which unique colour? ","Chartes Blue","Chartes Green","Chartes Red","Chartes White","Geography",3},
{"In which country is the port of Odense?","Denmark","Sweden","Norway","Finland","Geography",3},
{"Which country's name means Sunday?","Dominica","Canada","Russia","Australia ","Geography",3},
{"The highest mountain in Japan is Mount Fuji. What does Fuji mean? ","fire","snow","beauty","harmony","Geography",3},
{"The only person with 5 stars for excellence on the Hollywood Boulevard Walk Of Fame?","Gene Autry","Diana Ross","Bing Crosby","George Burns","Geography",3},
{"Which country does not border Slovakia?","Germany","Hungary","Austria","Poland","Geography",3},
{"In which country does the volcano Unzen grumble?","Japan","Indonesia","Philippines","Iceland","Geography",3},
{"Who was the Hollywood star who used his nose rather than hands or feet to make an impression in the sidewalk in front of 'Grauman's Chinese'?  ","Jimmy Durante","Lassie","Bob Hope","Karl Malden","Geography",3},
{"In which country does the volcano Mt Pelee grumble?","Martinique","Iceland","USA","Italy","Geography",3},
{"Which country produces the most silver?","Mexico","Canada","USA","Brazil","Geography",3},
{"In which country does the volcano Popocatepetl grumble?","Mexico","Colombia","Indonesia","Greece","Geography",3},
{"Which country does not border Libya?","Morocco","Tunisia","Algeria","Eygpt","Geography",3},
{"What is the most populated city north of the arctic circle?","Murmansk","Ottawa","Aberdeen","Fairbanks","Geography",3},
{"In which country does the volcano Ruapehu grumble?","New Zealand","USA","Indonesia","Japan","Geography",3},
{"According to the 'Global Peace Index' what is the safest country in the world?","Norway","Canada","Switzerland","Australia","Geography",3},
{"The Taj Mahal. Taj means 'crown', what does Mahal mean?","palace","king","queen","crypt","Geography",3},
{"Which street in London takes its name from a croquet like game once played by Charles I ?","Pall Mall","Threadneedle","Portobello","Piccadilly","Geography",3},
{"Which 'street' in London takes its name from the ornamental collars once made by the  17th century tailor Robert Baker?","Piccadilly","Pall Mall","Threadneedle","Carnaby","Geography",3},
{"Which country produces the most amber?","Poland","Canada","India","China","Geography",3},
{"The largest industrial complex in the world in the 19th century was found in which English harbour city?","Portsmouth","Liverpool","Newcastle","Dover","Geography",3},
{"Which country is not on the shores of Lake Victoria?","Rwanda","Uganda","Kenya","Tanzania","Geography",3},
{"The most visited city in Brittany has the highest ratio of sea food restaurants in Europe. Which port city is it?","Saint Malo","Rennes","Lannion","Brest","Geography",3},
{"A native indian legend claims that the scored marks that run down the side of Devil's Tower in Wyoming were gouged by a giant bear that was trying to reach what?","Seven stranded young maidens","The honey coloured sun ","His own shadow","The other end of the rainbow","Geography",3},
{"What are the winds called below the latitude 60 degrees south?","Shrieking 60s","Screaming 60s","Scary 60s","Sullen 60s","Geography",3},
{"Which Saint is not a US Virgin Island?","St Vincent","St John","St Croix","St Thomas","Geography",3},
{"Which country does not border Syria?","Sudan","Isreal","Lebanon","Turkey","Geography",3},
{"In which South American country would you find the city New Amsterdam?","Surinam","Brazil","Ecuador","Guyana","Geography",3},
{"What is found on the flag of Rwanda?","The letter 'R'","A Star","A Half Moon","An Assualt Rifle","Geography",3},
{"In which country does the volcano Kilauea grumble?","USA","Japan","Iceland","Spain","Geography",3},
{"How many seats did the Spitfire fighter plane have?",1,2,3,"None","History",1},
{"How many wives did Henry VIII have?",6,5,8,4,"History",1},
{" How many years did the '21 Year War'  between Sweden and Russia last? ",21,2,55,103,"History",1},
{"How many pennies were there in a pre decimal pound?",240,100,200,140,"History",1},
{"In which year was the Gunpowder Plot?",1605,1705,1805,1505,"History",1},
{"What year saw Adolph Hitler committing suicide?",1945,1944,1946,1947,"History",1},
{"In which year did JFK get assassinated?",1963,1966,1968,1960,"History",1},
{"In what year was the Falkland war?",1982,1984,1980,1978,"History",1},
{"In which year did a US-led coalition invade Iraq?",2003,2001,2005,1999,"History",1},
{"Which country did the USSR invade in 1979?","Afghanistan","Iraq","Iran","China","History",1},
{"What was banned in USA in January 1920?","Alcohol","Gambling","Strikes","Smoking","History",1},
{"One of the ancient world wonders, the 'Hanging Gardens', was found in which city?","Babylon","Alexandria","Rome","Athens","History",1},
{"What was named after a hydrogen bomb test?","Bikini","Hoola Hoop","Frisbee","Matchbox","History",1},
{"Robben Island was a prison near which city?","Cape Town","San Francisco","Athens","Exeter","History",1},
{"Iceland and the Uk were caught up in which war?","Cod","Herring","Salmon","Lobster","History",1},
{"King William the Bastard was also known by which other name?","Conqueror","Rufus","Orange","Young King","History",1},
{"Of which country was Greenland a colony until 1981?","Denmark","Sweden","Russia","Iceland","History",1},
{"The patron saint of England is famous for killing which type of creature?","Dragon","Unicorn","Angel","Devil","History",1},
{"William Kemmler, back in 1890, was the first person to be killed using what lethal method?","Electric Chair","Lethal Injection","Death by Firing Squad","Radiation","History",1},
{"What was special about Louise Brown, born July 25, 1978 in England?","First test tube baby","First surrogate mother","First surviving separated Siamese twin","First surviving 20 week old foetus","History",1},
{"During the second world war in Germany it was forbidden to give a horse which name?","Hitler","Stalin","Mussolini","Winston","History",1},
{"Who shot Lee Harvey Oswald?","Jack Ruby","Jack Diamond","Jack Emerald","Jack Sapphire","History",1},
{"What was the first name of the US President known by the nickname JFK?","John","Joe","Jerry","Jack","History",1},
{"Which explorer was the first to circumnavigate the globe?","Magellan","Drake","Marco Polo","Columbus","History",1},
{"What species were Benjy and Laska, who were sent into space in 1958?","Mice","Rats","Monkeys","Cats","History",1},
{"Which European country is ruled by The House of Orange?","Netherlands","Belgium","Sweden","Norway","History",1},
{"What was the name of Christopher Columbus' smallest  ship?","Nina","Tina","Gina","Mina","History",1},
{"What nationality was Roald Amundsen, the first man to reach the South Pole?","Norwegian","Swedish","Dutch","Belgian","History",1},
{"In what industry did John Davidson Rockefeller get rich?","Oil","Motor","Music","Movie","History",1},
{"Who was Pakistan's President in 2006?","Pervez Musharraf","Pratibha Patil","Nawaz Sharif","Benazir Bhutto","History",1},
{"Which organisation was awarded the Nobel Peace Prize in 1917?","The Red Cross","The Boy Scouts","The Police","Fathers for Justice","History",1},
{"What was 10th century English king Ethelred's nickname?","The Unready","The Unlucky","The Unshaven","The Unsweetened","History",1},
{"Queen Elizabeth I of England was also known by which name?","The virgin queen","The ginger queen","The Richmond queen","Bloody queen Elizabeth","History",1},
{"What weather phenomenon was the Norse god Thor thought to control? ","Thunder","Lightening","Typhoon","Earthquakes","History",1},
{"King Henry VII of England was a member of which royal house?","Tudor","York","Lancaster","Stuart","History",1},
{"Which Swedish motor vehicle manufacturer acquired the Dutch company DAF in the mid-1970s?","Volvo","Saab","Ford","Dacia","History",1},
{"Where did Napoleon Bonaparte suffer his last defeat? ","Waterloo","Rome","Elba","Leipzig","History",1},
{"How many baths did Louis XIV take in his lifetime?",3,0,51,1,"History",2},
{"How many brothers and sisters did John F. Kennedy have?",8,3,0,2,"History",2},
{"How many days were there in one week in ancient Roman times?",8,7,6,10,"History",2},
{"Out of every 10 women in Scotland, how many were pregnant on their wedding day, according to a Royal Commission of 1868?",9,5,0,2,"History",2},
{"How many kings of England have been named Edward? ",9,5,4,7,"History",2},
{"How many people are there in a US Grand Jury?",23,12,11,17,"History",2},
{"An estimated how many Popes have been murdered?",26,6,13,46,"History",2},
{"How many days was William Harrison President of the United States?",32,64,16,8,"History",2},
{"How many years were there between the Silver Jubilees of George V and Elizabeth II? ",42,32,52,62,"History",2},
{"How many km long was the Berlin Wall?",42,22,82,12,"History",2},
{"For how many years did Queen Victoria reign?",63,53,43,73,"History",2},
{"In Roman Numerals what does LXX stand for?",70,120,60,1200,"History",2},
{"How many pilgrims left Plymouth for America on the Mayflower?",104,202,64,264,"History",2},
{"How many years did the 'One Hundred Years War' last?",114,100,99,144,"History",2},
{"How many minutes did Neil Armstrong spend on the moon?",152,62,"1,162",12,"History",2},
{"According to Forbes new Rich List for 2009, how many billionares are there in the world? ",793,241,"2,355","5,205","History",2},
{"In which year did King Richard the 'lionhearted' die?",1199,99,599,1599,"History",2},
{"In which year did Henry VIII die?",1547,1597,1647,1507,"History",2},
{"What number on Pennsylvania Avenue would you find the white house?",1600,1200,1800,2000,"History",2},
{"In which year was St Pauls cathedral completed?",1711,1611,1811,1911,"History",2},
{"In which year was the revolver invented?",1835,1888,1788,1802,"History",2},
{"The Spanish Dublone was legal tender in the USA until which year?",1857,1777,1657,1927,"History",2},
{"In which year did electricity replace steam powered locomotives in the London Underground?",1890,1910,1850,1930,"History",2},
{"In which year was the Tower Bridge in London completed?",1894,1794,1811,1911,"History",2},
{"What year did the infamous San Francisco earthquake take place?",1906,1916,1896,1926,"History",2},
{"In which year was the first successful Channel crossing by an airplane?",1909,1903,1913,1897,"History",2},
{"In which year did the Titanic sink?",1912,1909,1915,1905,"History",2},
{"In which year was the infamous 'black sox' scandal?",1919,1909,1929,1939,"History",2},
{"In what year was Mahatma Gandhi assassinated?",1948,1950,1942,1938,"History",2},
{"In which year was the first successful heart transplant performed?",1967,1957,1977,1947,"History",2},
{"In which year was Prince Charles invested as The Prince of Wales?",1969,1979,1959,1989,"History",2},
{"In which year did the Rainbow Warrior sink?",1985,1986,1987,1984,"History",2},
{"In which year was Rajiv Gandhi assassinated?",1991,1981,1971,2001,"History",2},
{"In which year was the EURO TUNNEL officially opened?",1994,1990,1998,1986,"History",2},
{"What was the worlds population in AD 1?","200,000,000","500,000,000","25,000,000","1 billion","History",2},
{"Which amendment of the US constitution abolished slavery?","13th","18th","9th","10th","History",2},
{"For how long did Queen Jane rule England?","9 days","9 years","9 weeks","9 months","History",2},
{"According to an old legend, who can't shed more than 3 tears?","a witch","a King","a lawyer","a bride ","History",2},
{"Who was the 2nd man in space?","Alan Shepard","John Glenn","Virgil Grissom","Scott Carpenter","History",2},
{"King Zog ruled which country?","Albania","Russia","Prussia","Persia","History",2},
{"What was the name of the research ship Charles Darwin travelled with?","Beagle","Eagle","Mermaid","Turtle","History",2},
{"Charles Darwin was a passenger on which research ship?","Beagle","Dolphin","Eagle","Albatross","History",2},
{"In which city was the Titanic built?","Belfast","Southampton","Glasgow","Liverpool","History",2},
{"Who was not the mayor of a US town?","Bruce Willis","Sony Bono","Anthony Hopkins","Clint Eastwood","History",2},
{"Which ship was the first to arrive and rescue Titanic survivors?","Carpathia","Arizona","George Washington","Bremen","History",2},
{"Which animal is not a Chinese year?","Cat","Dragon","Pig","Rooster","History",2},
{"Who was the first wife of King Henry VIII?","Catherine of Aragon","Anne Boleyn","Jane Seymour","Anne of Cleeves","History",2},
{"Which English Monarch succeeded James I?","Charles I","James II","William III","Mary II","History",2},
{"The Gregorian Calendar was adopted by which country in 1912?","China","Persia","India","Ireland","History",2},
{"Which country was not a Portugese colony?","Colombia","Brazil","Angola","Mozambique","History",2},
{"Which word from the inaugural address by Barack Obama was cut out of the speech whilst being broadcast in China?","Communism","Chinese","Tibet","Earthquakes","History",2},
{"What was the name of Wellington's horse?","Copenhagen","Paris","Rome","Washington","History",2},
{"Florence Nightingale achieved fame during which war?","Crimean","First World War","Boer War","100 Years War","History",2},
{"Which animal is not a Chinese year?","Crow","Ox","Pig","Monkey","History",2},
{"Which animal is not a Chinese year? ","Dolphin","Dog","Monkey","Goat","History",2},
{"Which English King died in 1553 at the age of 15?","Edward VI","Edward V","Edward VII","Edward IV","History",2},
{"The crown of which New York City landmark was originally built as an airship dock?","Empire State Building","Chrysler Building","Statue of Liberty","Trump Tower","History",2},
{"What was the 1969 war between El Salvador and Honduras called?","football","cod","cola","postage stamp","History",2},
{"Which English King bought Buckingham Palace?","George III","George II","Charles I","Charles II","History",2},
{"Which US President said \"I cannot tell a lie\"?","George. Washington","George W Bush","Richard Nixon","Bill Clinton","History",2},
{"Which language did King George I speak?","German","Latin","French","Russian","History",2},
{"Which King Harold died during the battle of Hastings?","Godwinson","Harefoot","the Elder","Ironside","History",2},
{"Which ancient world wonder was found in Giza?","Great Pyramid","Lighthouse","Temple Of Artemis","Statue Of Zeus","History",2},
{"What was Ehrich Weiss better known as?","Harry Houdini","Charlie Chaplin","The Great Suprendo","David Copperfield ","History",2},
{"On which island was Capt Cook killed in 1779?","Hawaii","Australia","New Zealand","Moluccan Islands","History",2},
{"The falsely accused WW I spy Mata Hari was from which country?","Holland","France","India","Italy","History",2},
{"Which country founded the West India Company?","Holland","France","Germany","Spain","History",2},
{"Diana was the Roman goddess of what?","Hunting","Passion","Beauty","War","History",2},
{"What country provided the birthplace of Christopher Columbus?","Italy","Spain","Portugal","France","History",2},
{"Which English Monarch was the first from the House of Stuart?","James I","Charles I","Henry VII","Edward IV","History",2},
{"Which English Monarch was succeeded by William III of Orange?","James II","James I","Charles II","Mary II","History",2},
{"Which English Monarch succeeded Charles II?","James II","James I","William III","Mary II","History",2},
{"Who hosted the music radio program The Perfumed Garden?","John Peel","Noel Edmunds","Kenny Everett","Vernon Kay","History",2},
{"Joseph Stalin twice ordered the KGB to assassinate which US actor?","John Wayne","Humphrey Bogart","Bob Hope","James Cagney","History",2},
{"The Mau Mau were terrorists in which country late 50s early 60s?","Kenya","Sudan","Malaysia","Ghana","History",2},
{"What was the name of the atom bomb dropped on Hiroshima?","Little Boy","Bad Boy","Fat Boy","Good Boy","History",2},
{"Which explorers expedition was the first to circumnavigate the earth?","Magellan","Cook","de Gama","Cartier","History",2},
{"Which English Monarch succeeded William III of Orange?","Mary II","James II","James I","Charles II","History",2},
{"Which famous outlaws last words were \"That's life\"?","Ned Kelly","Al Capone","Dick Turpin","Billy the Kid","History",2},
{"In which month of 1987 was weatherman Michael Fish embarrassed for failing to give warning of severe gales?","October","September","December","August","History",2},
{"Which English Monarch was also known as Old Ironsides","Oliver Cromwell","Richard Cromwell","Charles I","Charles II","History",2},
{"From which country did Bangladesh claim its independence?","Pakistan","India","China","Britain","History",2},
{"Where did the 30 years war start and finish?","Prague","Berlin","London","Paris","History",2},
{"Which member of the British Royal Family was made Deputy Sheriff of Harris County, Texas in 1960?","Prince Philip","Prince Charles","The Queen","Prince Andrew","History",2},
{"Who directly succeeded King Edward VI as Monarch of England?","Queen Jane","Queen Mary I","Queen Elizabeth I","King James I","History",2},
{"Seti I was the father of which Egyptian?","Ramesses II","Tutankhamun","Nefertiti","Cleopatra","History",2},
{"Julius Caesar said \"The die is cast\" after crossing which river?","Rubicon","Thames","Tiber","Danube","History",2},
{"The crossing of which river started a civil war?","Rubicon","St. Lawrence","Avon","Danube","History",2},
{"What kind of march did Gandhi lead?","Salt","Pepper","Sugar","Flower","History",2},
{"Which city was destroyed by an earthquake in 1906?","San Francisco","Naples","Lisbon","Havana","History",2},
{"What was the name of the flu that killed an estimated 40 million people in 1918?","Spanish","Asian","Hong Kong","European","History",2},
{"Olaf Palme was assassinated in 1986. Of which country was he the prime minister?","Sweden","Norway","Finland","Denmark","History",2},
{"What was sometimes used as currency in 18th century Siberia?","Tea","Coffee","Snow","Tulips","History",2},
{"What did Captain Cook call the Islands of Tonga?","The Friendly Islands","The Scary Islands","The Tongan Islands","The Cook Islands","History",2},
{"Which of these radio programmes did John Peel once present?","The perfumed garden","The poisoned garden","The tendered garden","The Musical garden","History",2},
{"Which major British newspaper closed down for almost a year in 1978?","The Times","The Sun","The Telegraph","The Mirror","History",2},
{"Which ancient world wonder was found in Alexandria?","The Lighthouse","Hanging Gardens","Temple Of Artemis","Great Pyramid","History",2},
{"The Rainbow Warrior was what form of transport?","Trawler","Cruise Ship","Tugboat","Oil Tanker","History",2},
{"What was the name of the cat that survived the sinking of the Bismark, HMS Cossack and the HMS Ark Royal in WW II ?","Unsinkable Sam","Unsinkable Molly Brown","Wet Willy","Kit Cat","History",2},
{"Marco Polo was a citizen of which city?","Venice","Rome","Florence","Naples","History",2},
{"Which animal is not a Chinese year?","Whale","Snake","Hare","Tiger","History",2},
{"In history, the highwayman Dick Turpin was hanged in which city?","York","London","Leeds","Portsmouth","History",2},
{"How many wheels had a hansom cab?",2,3,4,5,"History",3},
{"How many seconds did it take Napoleons surgeon Baron Dominique Larrey to amputate a leg?",14,3,32,60,"History",3},
{"How many swings of the axe did it take to remove Maria Stuarts head?",15,1,3,35,"History",3},
{"How many dollars did the first settlers pay the native Indians for Manhattan Island?",24,4,48,96,"History",3},
{"Concubines excluded, how many wives did a Chinese Emperor have?",40,1,13,88,"History",3},
{"According to legend, how many bears did Davy Crockett kill in 7 months? ",105,7,77,705,"History",3},
{"How old was the Biblical figure Methusalem?",969,844,622,369,"History",3},
{"In which year were the Salem witchcraft trials?",1692,1581,1744,1519,"History",3},
{"In which year was the last legal execution of a witch in Scotland?",1727,1827,1927,1627,"History",3},
{"In which year was the lightning rod invented?",1752,1322,1825,1901,"History",3},
{"In which year did New York become a US state?",1788,1819,1792,1837,"History",3},
{"In which year did the first steam ship cross the Atlantic?",1819,1910,1859,1780,"History",3},
{"The age of the railway began in which year with the introduction of the Liverpool-Manchester line?",1830,1800,1860,1770,"History",3},
{"In which year did the first passenger die in a rail accident?",1830,1850,1780,1870,"History",3},
{"In which year were postage stamps introduced?",1840,1899,1745,1650,"History",3},
{"In which year did Texas become a US state?",1845,1912,1959,1861,"History",3},
{"The first weather report in a newspaper appeared in which year?",1848,1788,1871,1902,"History",3},
{"In which year were blue jeans invented?",1874,1836,1902,1580,"History",3},
{"In which year was the light bulb invented?",1880,1901,1825,1911,"History",3},
{"In which year did Oklahoma become a US state?",1907,1889,1850,1819,"History",3},
{"In which year did New Mexico become a US state?",1912,1867,1959,1788,"History",3},
{"In which year were false eyelashes invented?",1916,1925,1939,1888,"History",3},
{"In which year did Charles Lindbergh fly solo across the Atlantic?",1927,1937,1917,1907,"History",3},
{"In which year was nylon invented?",1935,1885,1906,1951,"History",3},
{"In which year was the transistor invented?",1947,1844,1902,1975,"History",3},
{"In which year was the microwave oven invented?",1947,1977,1921,1982,"History",3},
{"In which year did the hula hoop craze first circle the world?",1958,1963,1952,1966,"History",3},
{"In which year was the Berlin wall built?",1961,1958,1946,1965,"History",3},
{"In which year was Nelson Mandela sentenced to life in prison?",1964,1972,1956,1978,"History",3},
{"In which year did the mini skirt first turn heads?",1964,1968,1958,1961,"History",3},
{"In which year was the first 'Great Blackout' in the eastern United States and Canada?",1965,1975,1955,1985,"History",3},
{"In which year was the 747 Jumbo jet introduced?",1970,1964,1978,1984,"History",3},
{"Timber selected from how many fully grown oak trees were needed to build a large 3 decker Royal Navy battle ship in the 18th century?","3,500",50,500,"1,500","History",3},
{"In 1970 the 'Blue Flame' became the first car to break which speed barrier?","1,000 km hr","250 km hr","500 km hr","1,500 km hr","History",3},
{"The 'football' or briefcase with the nuclear codes must always be within how many metres of the US President?","12 m","6 m","2 m","24 m","History",3},
{"How long did the Apollo 11 mission last?","195 hours 18 min","95 hours 18 min","295 hours 18 min","495 hours 18 min","History",3},
{"What was the average life expectancy of an Englishman in the middle ages?","33 years","13 years","21 years","41 years","History",3},
{"How long was the war between GB  and Zansibar in 1896?","38 min","38 sec","38 hours","38 days","History",3},
{"How long did the Wright Brothers first flight last?","59 sec","12 sec","3 sec   ","24 sec","History",3},
{"What was the cargo on board the HMS Bounty?","Breadfruit","Grapefruit","Sauerkraut","Watermelon","History",3},
{"Who was Patrick Stewart's best man at his wedding?","Brent Spiner","William Shatner","LeVar Burton","Johnathan Frakes","History",3},
{"Off the coast of which country did the Edmund Fitzgerald sink?","Canada","Ireland","Scotland","Australia","History",3},
{"The press coined which famous pilot 'The Flying Fool' in 1927?","Charles Lindbergh","Baron von Richtofen","Orville Wright","Amelia Earhart","History",3},
{"In which country did an earthquake kill an estimated 650,000 people in 1976?","China","Pakistan","Mexico","Japan","History",3},
{"Punch editor A P Herbert once wrote a cheque on the side of a what?","cow","bus","taxi","egg","History",3},
{"The USA bought the Virgin islands from which country?","Denmark","GB","Holland","France","History",3},
{"Which city was never the capital of the USA?","Detroit","New York ","Baltimore","Philadelphia","History",3},
{"Tollbooth was an infamous 18th century prison in which city?","Edinburgh","Halifax","London","Bristol","History",3},
{"Which queen at one time banned the use of mirrors?","Elizabeth I ","Elizabeth II ","Mary","Freddie Mercury","History",3},
{"How often does Airforce One undergo a complete overhaul or D-Check?","every 154 days","every 54 days","every 254 days","every 354 days","History",3},
{"In the 1930s, what was the 'Phalange'?","Fascist movement in Spain","Secret police in Italy","Abstract art movement","Dance craze","History",3},
{"The NAZIS declared war on which country 3 March 1945?","Finland","Japan","France","Italy","History",3},
{"What did the Roman Catholic church condemned in the 16th century?","fork","spoon","corkscrew","knife","History",3},
{"Off the coast of which country did the Amoco Cadiz sink?","France","USA","Spain","South Africa","History",3},
{"The Roman province Aquitania was found in which modern day country?","France","Scotland","Portugal","Austria","History",3},
{"Which explorer first entered San Francisco Bay in 1579?","Francis Drake","Juan Ponce de Leon","Henry Hudson","Amerigo Vespucci","History",3},
{"Baby Doc Duvalier was the dictator of which country?","Haiti","Senegal","Vietnam","Algeria","History",3},
{"Herodotus is known as the father of what?","History","Medicine","Theatre","Music","History",3},
{"Between which two countries was the 1969 'Football War'?","Honduras and El Salvador","Brazil and Argentina","Algeria and Tunisia"," Chile and Peru ","History",3},
{"Off the coast of which country did the QE I sink?","Hong Kong","USA","Brazil","Spain","History",3},
{"Which ship sank in the Denmark Strait?","Hood","Bismark","Titanic","Exon Valdez","History",3},
{"Which country invented Venetian Blinds?","Japan","Italy","France","USA","History",3},
{"Who was the captain of PT 109?","JFK","Ronald Reagan","George Bush sr","Gerald Ford","History",3},
{"Who was William Shatner's best man at his wedding?","Leonard Nimoy","Brent Spiner","DeForest Kelley","James Doohan","History",3},
{"Which magazine first published photos of a human embryo in 1965?","Life","Time","Newsweek","Cosmopolitan ","History",3},
{"Which PM played a role in the development of soft ice cream?","Margret Thatcher ","Tony Blair","Winston Churchill ","William Pitt","History",3},
{"Botany Bay was the first penal colony in which Australian state?","New South Wales","Tasmania","South Australia","Queensland","History",3},
{"Which kind of animal did Florence Nightingale often carry around in her pocket?     ","Owl","Snake","Puppy","Kitten","History",3},
{"Which is the oldest airline in the English-speaking world?","Quantas","British Airways","American Airlines","Air Lingus","History",3},
{"What kind of animal was the germanic goddess of the spring?","rabbit","fox","bluebird","wolf","History",3},
{"Between 1807 and 1821 the capital of Portugal was found in which city?","Rio de Janeiro","London","Madrid","Goa","History",3},
{"Who was Australia's longest serving Prime Minister?","Robert Menzies","John Howard","Gough Whitlam","Bob Hawke","History",3},
{"Who was the first man to claim he reach the North Pole in 1909?","Robert Peary","Roald Amundsen","Robert Scott","Admiral Halsey","History",3},
{"The Roman province Lusitania was found in which modern day country?","Spain","France","Ireland","Germany","History",3},
{"Which Sunday newspaper, in 1924, published the first crossword to appear in a British Newspaper?","Sunday Express","Sunday Times","The Observer","Sunday Mirror","History",3},
{"Which Prime Minister helped invent soft ice-cream?","Thatcher","Wilson","Major","Callaghan","History",3},
{"What was TIME magazines man of the year in 1982?","The Computer ","The Red Cross","The Automobile","NASA","History",3},
{"Which of the Seven Wonders of the Ancient World was found in Halicarnassus?","The Mausoleum","The Temple of Artemis","The Hanging Gardens","The Lighthouse","History",3},
{"Off the coast of which country did the USS Arizona sink?","USA","Australia","Ireland","Canada","History",3},
{"What name did the Vikings give to present day Newfoundland?","Vinland","Graceland","No mans Land","Ice Land","History",3},
{"Which US state did Sir Walter Raleigh name?","Virginia","Massachusetts","Rhode Island","Florida","History",3},
{"Who was Ronald Reagan's best man at his wedding?","William Holden","Cary Grant","Charlie Chaplin","Humphrey Bogart","History",3},
{"Which Thomas was executed alongside Guy Fawkes in November 1605?","Winter","May","Summer","March","History",3},
{"Which general defeated the French in Canada?","Wolfe","Hawke","Lambe","Hogge","History",3},
{"How many ghosts visit Scrooge in A Christmas Carol?",4,3,2,5,"Literature",1},
{"Which female novelist wrote the book Black Beauty?","Anna Sewell","Barbara Cartland","Enid Blyton","Dorothy L Sayers","Literature",1},
{"What was the name of Roy Rogers' pet dog?","Bullet","Fido","Lightening","Dog Rogers","Literature",1},
{"Which book begins with the line \"Most motorcars are conglomerations....\" ?","Chitty Chitty Bang Bang","The Little Engine That Could","War of the Worlds","Mary Poppins","Literature",1},
{"Who wrote 'a clockwork orange'?","Anthony Burgess","Arnold Burgess","Anthony Hopkins","Arnold Hopkins","Literature",1},
{"What was Eric Blair’s pen name?","George Orwell","H.G. Wells","John Steinbeck","Charles Dickens","Literature",1},
{"What was the name of the dog of Dennis the menace?","Gnasher","Basher","Thrasher","Smasher","Literature",1},
{"Which is the longest of Shakespeare’s plays?","Hamlet","MacBeth","2 Gentlemen of Verona","Romeo and Juliet","Literature",1},
{"Which of the following is not a Romance author?","Harold Robbins","Barbara Cartland","Danielle Steel","Jackie Collins","Literature",1},
{"What John Spyri story is about a girl who lives in the Alps?","Heidi","Annie","Emily","Carmen","Literature",1},
{"In which month did Samuel Pepys begin his famous diary?","January","March","May","July","Literature",1},
{"At which railway station does one board the 'Hogwarts Express'?","Kings Cross","Waterloo","Victoria","Charing Cross","Literature",1},
{"Which of the following is not a childrens author?","Michael Crichton","Dr. Seuss","Enid Blyton","Roger Hargreaves","Literature",1},
{"What was the name of Sherlock Holmes house keeper?","Mrs Hudson","Mrs Sippi","Miss Mayweather","Mrs Wilson","Literature",1},
{"Michael Bond was the creator of which bear?","Paddington","Yogi","Pooh","Baloo","Literature",1},
{"Which book begins with the line \"All children except one, grow up....\" ?","Peter Pan","Mary Poppins","The Jungle Book","The lion. the witch and the wardrobe","Literature",1},
{"Whose nose grew when he told a lie?","Pinocchio","Dumbo","Jeffrey Archer","Peter Pan","Literature",1},
{"Carlo Collodi created which famous children's character?","Pinocchio","Dumbo","Snow White","Peter Pan","Literature",1},
{"What is Dick Grayson better known as?","Robin","Batman","Joker","Alfred","Literature",1},
{"Where was William Shakespeare born?","Stratford Upon Avon","Bath","Bradford","Kingston Upon Thames","Literature",1},
{"What is the subtitle of Peter Pan?","The Boy Who Wouldn’t Grow Up","The Boy With The Growing Nose","The Puppet That Came Alive","The Boy Who Lied","Literature",1},
{"Which book begins with the line \"Dorothy lived in the midst....\" ?","The Wonderful Wizard of Oz","Mary Poppins","The Thorn Birds","Mists of Avalon","Literature",1},
{"Which of the following is the best-selling fiction author of all time?","William Shakespeare","Agatha Christie","Barbara Cartland","Harold Robbins","Literature",1},
{"How many Bronte sisters were there?",3,2,4,5,"Literature",2},
{"How many children were in Enid Blytons the famous five?",4,5,6,3,"Literature",2},
{"Winston Smith is the central character in which book?",1984,"The Time Machine","Dune","The Day Of The Triffids","Literature",2},
{"How many rode into Tennyson's 'valley of death'?",5000,1000,500,100,"Literature",2},
{"How old was Adrian Mole?","13 and 3 quarters","13 and a half","13 and 3 fifths","13 and 2 thirds","Literature",2},
{"What was the name of inn in Treasure Island?","Admiral Benbow","Captain Benbow","Corporal Benbow","Officer Benbow","Literature",2},
{"Who wrote \"don't count your chickens before they are hatched\"?","Aesop","Shakespeare","Ben  Franklin","Chaucer","Literature",2},
{"Which of the following is the second best-selling fiction author of all time?","Agatha Christie","William Shakespeare","Barbara Cartland","Harold Robbins","Literature",2},
{"Who wrote 'The Count of Monte Christo'?","Alexandre Dumas","Victor Hugo","Nathaniel Hawthorne","Herman Melville","Literature",2},
{"Which name is not a Steven King book?","Cacy","Carrie","Cujo ","Christine","Literature",2},
{"Which book begins with the line \"These two very old people are the father and mother of Mr Bucket...\"?","Charlie and the Chocolate Factory","Peter Pan","Mary Poppins","Treasure Island","Literature",2},
{"Which of the following is not visited by Gulliver in Gulliver's Travels?","China","Japan","Lilliput","Laputa","Literature",2},
{"Who wrote 'Moll Flanders'?","Daniel DeFoe","Johnathan Swift","Voltaire","Henry Fielding","Literature",2},
{"Who wrote In The Beginning I Used To Be An Animal But I'm Alright Now?","Eric Burdon","Wayne Rooney","Scary Spice","Vinnie Jones","Literature",2},
{"What is the complete title of Mary Shelley's Frankenstein?","Frankenstein or The modern Prometheus","Frankenstein or The modern genesis","Frankenstein or The modern satan","Frankenstein or The modern phoenix","Literature",2},
{"Who wrote 'Pygmalion'?","G B Shaw","Mark Twain","Tolstoj","Emily Bronte","Literature",2},
{"Which of these writers died in 1400?","Geoffrey Chaucer","William Shakespeare","Daniel DeFoe","Samuel Johnson","Literature",2},
{"What was Mary Ann Evans pen name?","George Eliot","George Orwell","George Sand","George Bernard Shaw","Literature",2},
{"Who wrote 'Tom Jones'?","Henry Fielding","Johnathan Swift","Daniel DeFoe","Herman Melville","Literature",2},
{"Aldous Huxley's book Brave New World was banned in which country?","Ireland","Canada","South Africa","USA","Literature",2},
{"Who wrote 'I Robot'?","Isaac Asimov","Jules Verne","H G Wells","Douglas Adams","Literature",2},
{"Who was Rowena's husband?","Ivanhoe","Robin Hood","Dick Turpin","Macbeth","Literature",2},
{"Who wrote 'Peter Pan'?","J M Barrie","Rudyard Kipling","Lewis Carroll","Carlo Collodi","Literature",2},
{"Who wrote the book The Last Of The Mohicans?","James Fenimore Cooper","H.G. Wells","Jules Verne","Sir Walter Scott","Literature",2},
{"Which book begins with the line \" The great fish moved silently...\" ?","Jaws","Moby Dick","The Old Man and the Sea","The Shipping News","Literature",2},
{"Who wrote 'The Spy Who Came In From The Cold'?","John le Carre","Ian Fleming","Henning Mankell","Arthur Conan Doyle","Literature",2},
{"Mother Raksha is a character in which childrens book?","Jungle Book","The Wonderful Wizard Of Oz","The Wind in the Willows","Peter Pan","Literature",2},
{"Uther Pendragon was which mans father?","King Arthur","Dick Turpin","Robin Hood","Ivanhoe","Literature",2},
{"Oliver Mellors is a central character in which novel?","Lady Chatterley's Lover","The Great Gatsby","Animal Farm","The World According To Garp","Literature",2},
{"Totally Frank is which Frank's autobiography?","Lampard","Sinatra","Zappa","Howard","Literature",2},
{"Who wrote the popular Simon Templar books?","Leslie Charteris","Dorothy L Sayers","John le Carre","Raymond Chandler","Literature",2},
{"What were the cities in Dickens’s A Tale Of Two Cities?","London and Paris","Rome and Florence","Venice and Rome","Paris and Florence","Literature",2},
{"Who is a bat in Jungle Book?","Mang","Hang","Bang","Fang","Literature",2},
{"Who wrote 'The Mists of Avalon'?","Marion Zimmer Bradley","J R R Tolkien","Joanne K Rowling","Terry Pratchett","Literature",2},
{"What was Samuel Langhorne Clemens pen name?","Mark Twain","Novalis","Jack London","Joseph Conrad","Literature",2},
{"What was the name of the paranoid android in Hitch Hikers Guide to the Galaxy?","Marvin","Gort","Wayne","Robby","Literature",2},
{"The Count of Monte Christo was in love with which woman?","Mercedes","Porsche","Lancia","Cadillac","Literature",2},
{"What are the cannibalistic beasts called in H.G. Wells book The Time Machine?","Morlocks","Warlocks","Yahoos","Triffids","Literature",2},
{"Whose autobiography was entitled 'The Long Walk To Freedom'?","Nelson Mandela","Mahatma Gandhi","Lenin","Martin Luther King","Literature",2},
{"Who does Mr Brownlow rescue?","Oliver Twist","Tom Jones","Huckleberry Finn","Tom Brown","Literature",2},
{"Which nationality is best-selling author Paulo Coelho?","Portuguese","Spanish","French","Italian","Literature",2},
{"What is comic book hero Roy of the Rovers' surname?","Race","Run","Rave","Rover","Literature",2},
{"Which Adams wrote Watership Down?","Richard","Douglas","Tony","Morticia","Literature",2},
{"Which king said \"A horse, a horse! my kingdom for a horse!\"?","Richard III","Henry VIII","Wenceslas","Arthur","Literature",2},
{"Who wrote 'Treasure Island'?","Robert Louis Stevenson","H G Wells","Jack London","Sir Walter Scott","Literature",2},
{"Who wrote the book 'Dr Jekyll and Mr Hyde'?","Robert Louis Stevenson","Sir Walter Scott","Iian Banks","Alister Maclean","Literature",2},
{"What Was the Title Of Alex Haleys Most Famous Work?","Roots","Boots","Coots","Toots","Literature",2},
{"Which novel begins with the line \"Early in the spring of 1750....\" ?","Roots","Tom Jones","The Great Gatsby","I, Claudius","Literature",2},
{"What school does Tom attend in Tom Brown’s school days?","Rugby","Eton","Harrow","Dulwich","Literature",2},
{"Who wrote the play 'Waiting for Godot'?","Samuel Beckett","George Bernard Shaw","Andrew Lloyd Webber","Vladimir Nabokov","Literature",2},
{"The jealous Athena turned Arachne into which kind of animal?","spider","snake","donkey","rat","Literature",2},
{"What was the title of George Bernard Shaw’s play about Joan of Arc?","St Joan","Joan of Arc","Joan D'arc","Our Joan","Literature",2},
{"Which of the following authors are not in the top ten best-selling literature authors of all time?","Stephen King","Agatha Christie","Danielle Steel","Gilbert Patten","Literature",2},
{"Holden Caulfield is the main character in which book?","The Catcher In The Rye","Catch 22","Moby Dick",1984,"Literature",2},
{"Which book begins with the line \"Once there were four children whose names were Peter, Susan, Edmond, and Lucy....\"?","The Lion, the Witch and the Wardrobe","Peter Pan","Mary Poppins","The Swiss Family Robinson","Literature",2},
{"Shylock is a character in which Shakespeare play?","The Merchant Of Venice","Measure For Measure","Othello","The Comedy Of Errors","Literature",2},
{"In The Lord of the Rings, what is the name of the inn in Bree?","The Prancing Pony","The Red Stallion","The Merry Mare","The Spotted Gelding","Literature",2},
{"In which book would one find the childlike human species named Elois?","The Time Machine","Day Of The Triffids","Brave New World","Dune","Literature",2},
{"In which book would one find the trog like human species named Morlocks?","The Time Machine","Dune","Brave New World","The Day Of The Triffids","Literature",2},
{"Who wrote 'The Hunchback of Notre Dame'?","Victor Hugo","Gustave Flaubert","Voltaire","Alexandre Dumas","Literature",2},
{"Who wrote 'Mrs Dalloway'?","Virginia Woolf","James Joyce","D H Lawrence","Graham Greene","Literature",2},
{"Who wrote 'The Lord of the Flies'?","William Golding","George Orwell","Aldous Huxley","Joseph Conrad","Literature",2},
{"How many tasks did Hercules have to fulfill?",12,6,8,24,"Literature",3},
{"How long did Robinson Crusoe spend on the island?","28 years, 2 months and 19 days","2 years, 8 months and 12 days","55 years, 4 months and 3 days","7 years, 9 months and 22 days","Literature",3},
{"Who was 'The Once and Future King'?","Arthur","Elvis","Idi Amin","Arargon","Literature",3},
{"Which sport is referred to in ‘Antony and Cleopatra’?","Billiards","Snooker","Pool","Darts","Literature",3},
{"Who is not one of King Lears daughters?","Celia","Cordelia","Goneril","Regan","Literature",3},
{"Lewis Carroll's book Alice's Adventures in Wonderland was banned in which country?","China","USA","France","Ireland","Literature",3},
{"Which book begins with the line \"Not too long ago, a monster came to the small town of Castle Rock...\" ?","Cujo","Harry Potter and the Scorcerer's Stone","Bram Stoker's Dracula","Frankenstein's Monster","Literature",3},
{"In Which Dickens Novel Does Mr Micawber Appear?","David Copperfield","Oliver Twist","A Christmas carol","Great Expectations","Literature",3},
{"Who wrote the book The Moons A Balloon?","David Niven","H.G. Wells","Jules Verne","Julie Andrews","Literature",3},
{"What was Casanova's first name?","Giacoma","Alberto","Benito","Francesco","Literature",3},
{"Which novel begins with the line \"My father's family name being Pirrip....\"?","Great Expectations","Charlie and the Chocalate Factory","Kidnapped","Little Women","Literature",3},
{"In which book would one find the character named 'Pip'?","Great Expectations","Wind in the Willows","Jurassic Park","Rob Roy","Literature",3},
{"What is the name of the cat in Shakespeare's Macbeth?","Greymalkin","Tybalt","Tao","Kitty","Literature",3},
{"Who wrote 'Finnegan's Wake'?","James Joyce","Bram Stocker","W B Yeats","Samuel Beckett","Literature",3},
{"What are the names of the two main characters in Diana Gabaldon's highland saga novels?","Jamie and Claire","Fergus and Fiona","Rab and Elizabeth","Hamish and Maggie","Literature",3},
{"Who wrote The Day of the Triffids?","John Wyndam","Stephen King","Douglas Adams","Jules Verne","Literature",3},
{"Which book begins with the line \"I will begin the story of my adventures....\" ?","Kidnapped","Roots","Kim","Mary Poppins","Literature",3},
{"Dan Brown's book The Da Vinci Code was banned in which country?","Lebanon","Ireland","Poland","Italy","Literature",3},
{"Which book begins with the line \"Even in high summer, Tintagel was a haunted place...\" ?","Mists of Avalon","The Once and Future King","The Wonderful Wizard of Oz","Rosemary's Baby","Literature",3},
{"Who lives at Number Four Privat Drive?","Mr and Mrs Dursley","Toad of Toad Hall","Mary Poppins","Winnie-The-Pooh","Literature",3},
{"What is the name of the man servant in 'Around the world in 80 days'?","Pas Partout","Cato","Giles","Machu Picchu","Literature",3},
{"What is the name of the ship in 'Moby Dick'?","Pequod","Essex","Boston","Surprise","Literature",3},
{"Mr Darcy is an arrogant gentleman in which novel?","Pride and Prejudice","A Passage to India","Animal Farm","The Great Gatsby","Literature",3},
{"Which novel begins with the line \"Last night I dreamt I went to Manderly again....\" ?","Rebecca","Little Women","Trainspotting","Roots","Literature",3},
{"Who wrote the poem A Red Red Rose?","Robert Burns","Shakespeare","Dante","Stephen King","Literature",3},
{"What is the name of Don Quixote's horse?","Rosinate","Betty","Isabella","Theresa","Literature",3},
{"Who wrote the poem The Lady of the Lake?","Sir Walter Scott","T.S. Eliot","King Henry VIII","Shakespeare","Literature",3},
{"In which town did Tom Sawyer live?","St Petersburg","Bern","Hamburg","Rome","Literature",3},
{"Which cartoonist created Spider Man?","Steve Ditko","Walt Disney","Gary Larson","Bob Montana","Literature",3},
{"Which novel begins with the line \"It was the best of times....\" ?","Tale of Two Cities","Rebecca","Trainspotting","Chitty Chitty Bang Bang","Literature",3},
{"Which book begins with the line \"The summer my father bought the bear...\" ?","The Hotel New Hampshire","The Jungle Book","The Godfather","Trainspotting","Literature",3},
{"Which book begins with the line \"Samuel Spade's jaw was long and bony....\" ?","The Maltese Falcon","Jaws","Harry Potter and the Sorcerer's Stone","The Last of the Mohicans","Literature",3},
{"Which book begins with the line \"The Duchy of Grand Fenwick...\" ?","The Mouse that Roared","Chitty Chitty Bang Bang","Kim","Harry Potter and the Sorcerer's Stone","Literature",3},
{"The title of which Pink Floyd album is also a chapter in 'The Wind In The Willows'?","The Piper At The Gates Of Dawn","Wish You Were Here","Meddle","Animals","Literature",3},
{"Which book begins with the line \" \"Hello, ship\" Jake Holman said under his breath...\" ?","The Sand Pebbles","Moby Dick","The Shipping News","A Night to Remember","Literature",3},
{"Which book begins with the line \"The American handed Leamus another cup of coffee....\" ?","The Spy Who Came In From The Cold","The Maltese Falcon","The Godfather","The Eye Of The Needle","Literature",3},
{"Which book begins with the line \"For many days we had been tempest tossed....\" ?","The Swiss Family Robinson","Moby Dick","The Shipping News","Robinson Crusoe","Literature",3},
{"Which novel begins with the line \"On December 8th, 1915, Maggie Cleary had her fourth birthday....\" ?","The Thorn Birds","The Hotel New Hampshire","Roots","Little Women","Literature",3},
{"Who wrote 'Utopia' in 1516?","Thomas More","William Shakespeare","Christopher Marlowe","Francis Bacon","Literature",3},
{"In which book is there an inn called Admiral Benbow?","Treasure Island","Peter Pan","Lord of the Rings","Gullivers Travels","Literature",3},
{"In the book The Last Of The Mohicans what was the name of Chingachgook's only son?","Uncas","Mingo","Lightfoot","Magua","Literature",3},
{"In which Italian city do Romeo and Juliet live?","Verona","Naples","Milano","Pisa","Literature",3},
{"Which two men are waiting for Godot?","Vladimir and Estragon","Bob and Ted","Benno and Babe","Pumpkin and Honey Bunny","Literature",3},
{"Which former conservative leader wrote a biography on William Wilberforce in 2007?","William Hague","John Major","Iain Duncan Smith","Michael Howard","Literature",3},
{"Which Prime Minister won a Nobel prize for literature?","Winston Churchill","William Pitt","Margret Thatcher","Tony Blair","Literature",3},
{"The jellyfish consists of how much water?","95%","85%","75%","65%","Science",1},
{"How many moons does Earth have?",1,0,2,8,"Science",1},
{"How many atoms are there in a molecule of water?",3,2,4,1,"Science",1},
{"Cows have how many stomachs?",4,1,2,3,"Science",1},
{"How many wisdom teeth does the average adult have?",4,6,8,2,"Science",1},
{"The octal numbering system consistes of how many digits?",8,2,4,6,"Science",1},
{"How many legs does a spider have?",8,6,10,12,"Science",1},
{"How many sides does a Nonogon have?",9,19,0,99,"Science",1},
{"In which year did Pfizer Inc introduce it's Viagra drug to the market?",1997,1987,1977,2007,"Science",1},
{"The binary system of numbers uses which two digits?","1 and 0","1 and 2","1 and 10","10 and 100","Science",1},
{"How many millimetres are there in one inch?","25.4 mm","10.4 mm","250.4 mm","100.4 mm","Science",1},
{"Which scientist was born in Germany in 1879, became a Swiss citizen in 1901 and later became a US citizen in 1940?","Albert Einstein","Max Planck","Niels Bohr","Ludwig Boltzmann","Science",1},
{"What lives in a Formicarium?","Ants","Turtles","Apes","Butterflies","Science",1},
{"What is removed during an appendectomy?","Appendix","Bone Marrow","Kidney","Tonsils","Science",1},
{"Who first argued that the world was not flat? ","Aristotle","Columbus","Archimedes","Magellan","Science",1},
{"Where did the dingo originate?","Australia","Africa","Asia","Europe","Science",1},
{"Which of the following colours would make you appear the slimest? ","Black","White","Pink","Orange","Science",1},
{"What is classified by the A B O system?","Blood","Skin Colour","Fingerprints","Genetics","Science",1},
{"What is the loudest animal on earth?","Blue whale","Cricket","Human","Howler monkey","Science",1},
{"What is the name of the small tracking file left by websites on your computer?","Cookie","Worm","Spider","Trojan","Science",1},
{"What can't a Giraffe do?","cough","run","sleep","hear","Science",1},
{"An Aberdeen Angus is a type of what?","Cow","Dog","Pig","Plant","Science",1},
{"What is the chemical symbol for Chromium?","Cr","Ch","Kr","Cm","Science",1},
{"What was the name of the supercomputer that defeated chess master Garri Kasparov in 1997?","Deep Blue","Deep Thought","Deep Waters","Deep End","Science",1},
{"Which of the following animals is believed to be the first to be domesticated?","Dog","Cat","Cow","Rabbit","Science",1},
{"What does a Joule unit measure?","Energy","Work","Pressure","Light","Science",1},
{"A tortoiseshell cat is most likely what?","Female","Deaf","Blind","Male","Science",1},
{"Pyrophobia is the fear of what?","Fire","Thunder","Skyscrapers","Plastic","Science",1},
{"According to Newton, mass times acceleration is equal to what?","Force","Power","Velocity","Torque","Science",1},
{"What does a Hertz unit measure?","Frequency","Energy","Pressure ","Radioactivity","Science",1},
{"If you had rubella what would you have caught?","German measles","Chicken Pox","Whooping cough","Mumps","Science",1},
{"Which country introduced the worlds first diesel locomotive in 1912?","Germany","United Kingdom","Unites States","France","Science",1},
{"Which of the following is a metal that will not rust?","Gold","Silver","Nickel","Zinc","Science",1},
{"Alopecia describes a person with a lack of what?","Hair","Red blood cells","teeth","Memory","Science",1},
{"Christopher Cockerel invented what?","Hovercraft","Cats Eyes on the road","Helecopter","Catamaran  ","Science",1},
{"Which is the largest planet in our solar system?","Jupiter","Saturn","Uranus","Earth","Science",1},
{"Where in your body is your patella?","Knee","Elbow","Neck","Foot","Science",1},
{"Where in the body is the Patella?","Knee","Shoulder","Hip","Skull","Science",1},
{"Which of the following metals is in a liquid state at room temperature","Mercury","Uranium","Sodium","Tungsten","Science",1},
{"What is the chemical symbol for Sodium?","Na","N","So","S","Science",1},
{"Which is the most common gas in the atmosphere?","Nitrogen","Oxygen","Helium","Carbon Dioxide","Science",1},
{"What is the most common blood type in humans?","O","A","A+","A-","Science",1},
{"What is not a primary colour?","orange","red","yellow","blue","Science",1},
{"What do botanists study?","Plants","Biology","Dentistry","Fossils","Science",1},
{"K is the chemical symbol for which element?","Potassium","Chromium","Sodium","Carbon","Science",1},
{"What plant does the Colorado beetle attack?","Potato","Carrot","Cabbage","Lettuce","Science",1},
{"Mammals of the Order Marsupialia have what unique feature?","Pouches","Night vision","Webbed feet","Powerful legs","Science",1},
{"What does a Pascal unit measure?","Pressure","Light","Radioactivity","Heat","Science",1},
{"Na is the chemical symbol for which element?","Sodium","Nitrogen","Potassium","Neon","Science",1},
{"With which name do we refer to a male cat?","Tomcat","Bobcat","Topcat","Fleabag","Science",1},
{"John Logie Baird is credited with which invention?","TV","Radio","Telephone","Gramaphone","Science",1},
{"What is the hottest planet in our solar system?","Venus","Mercury","Mars","Earth","Science",1},
{"Tim Berners-Lee is known as the inventor of what?","World Wide Web","Apple Computers","Computer Mouse","Email","Science",1},
{"Which plant gives absynthe its hallucinogenic properties?","wormwood","holly","mistletoe","juniper","Science",1},
{"Which temperature has the same value in degrees in both centigrade and Fahrenheit?",-40,0,37,-273,"Science",2},
{"How many moons does Venus have?",0,1,2,3,"Science",2},
{"What percentage of US dogs are overweight?","40%","80%","60%","10%","Science",2},
{"How many feet in a fathom?",6,8,12,36,"Science",2},
{"In computing how many bits make one byte?",8,16,12,4,"Science",2},
{"How many arms does a squid have?",10,8,6,12,"Science",2},
{"How many sides does a dodecagon have?",12,10,20,22,"Science",2},
{"What was the number of the last Apollo mission?",17,13,29,14,"Science",2},
{"How many moons does Saturn have?",18,8,28,48,"Science",2},
{"On average, how many hours a day does a Koala bear spend sleeping?",22,2,12,8,"Science",2},
{"How many miles must one walk in order to burn off a pound of fat?",34,4,14,64,"Science",2},
{"According to Guinness what is the record number of children borne by one woman?",69,26,43,88,"Science",2},
{"How many nuclear power plants are there in the USA?",109,59,209,509,"Science",2},
{"How many chemical elements are there?",112,212,312,412,"Science",2},
{"How many litres are there in a barrel of oil?",159,59,29,189,"Science",2},
{"The first robot was introduced in which year?",1921,1941,1951,1891,"Science",2},
{"The Bikini was a concept by Louis Réard, but in which year?",1946,1966,1926,1906,"Science",2},
{"The first working computer mouse was developed by Douglas Engelbart in which year?",1963,1973,1983,1993,"Science",2},
{"The LCD or Liquid Crystal Display was first developed by James Fergason in which year?",1971,1981,1961,1951,"Science",2},
{"The world's firsr pocket calculator was invented by the Sharp Corporation in which year?",1971,1981,1991,1961,"Science",2},
{"In which year did Ernő Rubik invent the Rubik's cube?",1974,1964,1984,1954,"Science",2},
{"The first Mobile phone was invented by Bell Labs in which year?",1977,1987,1982,1972,"Science",2},
{"The Compact Disc was first developed by Philips Electronics and Sony Corp and released in which year?",1980,1985,1990,1975,"Science",2},
{"DNA fingerprinting was first explained to the world by Alec Jeffreys in which year?",1985,1975,1965,1995,"Science",2},
{"In which year was the satellite Galileo launched?",1989,1979,1999,1969,"Science",2},
{"In which year did Tim Berners-Lee introduce the phrase World Wide Web?",1990,1985,1995,1980,"Science",2},
{"How many muscles are there in an elephants trunk?","40,000","4,000",400,40,"Science",2},
{"How many feet long was the largest Blue Whale ever seen?","110 ft","55 ft","210 ft","550 ft","Science",2},
{"What speed can a human reach in free fall?","155 miles per hr","225 miles per hr","55 miles per hour","355 miles per hour","Science",2},
{"The first ballpoint pen was invented by Laszlo Biro in which decade?","1930s","1950s","1960s","1910s","Science",2},
{"The world's first microwave oven was built and demonstrated by Percy Spencer in which decade?","1940s","1960s","1970s","1980s","Science",2},
{"In which decade did the World Health Organisation declare Smallpox eradicated?","1970s","1960s","1980s","1950s","Science",2},
{"What generation is the so-called EDGE technology?","2.75G","2.5G","2G","3G","Science",2},
{"On average, how long does a giraffe sleep each day?","20 min","2 min","2 hours","20 hours","Science",2},
{"How much taller is the Eiffel tower in the summertime?","6 inches","6 feet","6 yards","0 inches","Science",2},
{"What is the sum of the internal angles in a hexagon?","720 degrees","360 degrees","1080 degrees","540 degrees","Science",2},
{"For how long is a dog pregnant?","9 Weeks","9 Days","9 Months","9 Fortnights","Science",2},
{"What are Lanthanides?","A block of elements in the periodic table","Mountains on Earth","Mountains on the Moon","Bacterium","Science",2},
{"In which continent did the ostrich originate?","Africa","Australia","North America","Asia","Science",2},
{"Which of the following insects requires no sleep?","Ant","Cockroach","Termite","Bee","Science",2},
{"What part of the body does a turtle use to breathe?","Anus","Belly","Shell","Mouth","Science",2},
{"What can you see with Kirlian photography?","aura","bones","blood cells","atoms","Science",2},
{"Animals of the Ursidae family are what?","Bears","Dogs","Apes","Horses","Science",2},
{"What colour skin does a polar bear have?","Black","White","Pink","Grey","Science",2},
{"What is an Ishihara test used for? ","Blindness","Pregnancy","Diabetes","Deafness","Science",2},
{"Cats are born with which colour eyes?","Blue","Grey","Brown","Red","Science",2},
{"What colour of tongue does the chow breed of dog have?","Blue","Red","Pink","Black","Science",2},
{"What colour is lobster blood?","Blue","Red","Clear","Yellow","Science",2},
{"What colour is octopus blood?","blue","red","green","yellow","Science",2},
{"What are bactrians and dromedaries?","Camels","Elephants","Bears","Sloths","Science",2},
{"Which element is present in all organic compounds?","Carbon","Calcium","Copper","Californium","Science",2},
{"What type of animal is considered good luck to have living at a theatre?","Cat","Dog","Bird","Mouse","Science",2},
{"A blue Orpington is a breed of which animal?","Chicken","Cat","Cow","Horse","Science",2},
{"Which of the following animals has the best memory?","Chimpanzee","Elephant","Donkey","Rhino","Science",2},
{"What did John Harrison invent in 1757?","chronometer","parking meter","taxi meter","thermometer","Science",2},
{"What was not the name of a US space mission?","Colombus","Galileo","Cassini","Magellan","Science",2},
{"Which beetle loves potatoes?","Colorado","Florida","Utah","Oregon","Science",2},
{"What did Douglas Engelbart invent in 1963?","Computer Mouse","Pocket Calculator","Email","Mobile Phone","Science",2},
{"What makes up 99.9% of the universe?","dark energy","H2O","stars","quarks","Science",2},
{"When cats have blue eyes they are also most likely what?","Deaf","Female","Male","Blind","Science",2},
{"A wapiti is a what?","Deer","Monkey","Bat","Rat","Science",2},
{"What kind of animal is a Lurcher?","Dog","Reptile","Fish","Bird","Science",2},
{"Cynophobia is the fear of what?","Dogs","China","The Dark","Spiders","Science",2},
{"Which of the following insects can fly at a speed of around 60 mph?","Dragonfly","Mosquito","Hornet","Bee","Science",2},
{"Which of the following mammals cannot jump?","Elephant","Giraffe","Hippo","Rhino","Science",2},
{"What was the name of the first digital computer?","ENIAC","MANIAC","PONTIAC","NICKNACK","Science",2},
{"Where in your body would you find the rods and cones?","Eyes","Ears","Fingers","Lungs","Science",2},
{"Which European country has the most nuclear power plants?","France","Russia","GB","Germany","Science",2},
{"Which type of bomb was invented by Edward Teller and Stanislaw Ulam in 1952?","Fusion","Fission","Bouncing","Napalm","Science",2},
{"Who said \"nature abhors a vacuum\"?","Galileo","Einstein","Aristotle","Newton","Science",2},
{"Which European country has sent the most people into space?","Germany","United Kingdom","Italy","Bulgaria","Science",2},
{"Where in Europe is the Barbary ape most likely found?","Gibralta","Greece","Bulgaria","Portugal","Science",2},
{"Which of the following animals are not rodents?","Hedgehogs","Rats","Gophers","Chipmunks","Science",2},
{"What does a 'Hippophagic' eat?","horse meat","dog meat","cat meat","whale meat","Science",2},
{"Ir is the chemical symbol for which element?","Iridium","Iron","Iodine","Iritum","Science",2},
{"What is a bird’s ‘gizzard’?","It’s second stomach","It's beak","It's tail feather","It's distinctive colour","Science",2},
{"What is the chemical symbol for Potassium?","K","P","Po","Ka","Science",2},
{"What are young squirrels called?","Kittens","Pups","Kids","Ankle biters","Science",2},
{"What are baby beavers called?","Kittens","Pups","Cubs","Pests","Science",2},
{"Mg is the chemical symbol for which element?","Magnesium","Manganese","Molybdenum","Tungsten","Science",2},
{"Mn is the chemical symbol for which element?","Manganese","Magnesium","Molybdenum","Tungsten","Science",2},
{"What is the scientific name for laughing gas?","Nitrous oxide","Carbon dioxide","Sulphur dioxide","Nitrous dioxide","Science",2},
{"What colour is an aircraft's black box?","Orange","Red","White","Black","Science",2},
{"With which name do we refer to a female cat?","Queen","Doe","Bitch","Kitty","Science",2},
{"What does a Becquerel unit measure?","Radioactivity","Energy","Pressure","Frequency","Science",2},
{"Which of the following animals can last the longest without water?","Rat","Camel","Human","Goat","Science",2},
{"The common cold is what kind of virus?","Rhino","Leo","Avian","Pisces","Science",2},
{"What is the chemical symbol for Antimony?","Sb","Ti","T","Sn","Science",2},
{"Which of the following is a theory in physics?","Schrodinger's Cat","Schrodinger's Rat","Schrodinger's Hat","Schrodinger's Bat","Science",2},
{"What was not the name of a US space mission?","Scout","Mariner","Ranger","Pioneer","Science",2},
{"What did Otto Frederick Rohwedder invent in 1928 that changed the world forever?","Sliced bread","RADAR","The refrigerator","The television","Science",2},
{"What does an OLF unit measure?","smell","taste","light ","heat","Science",2},
{"What is the chemical symbol for Tin?","Sn","Ti","T","Sb","Science",2},
{"On the Mohs scale the hardest substance is diamond - what's the softest?","Talcum Powder","Wheat Flour","Sugar","Skin dust","Science",2},
{"What is the chemical symbol for Titanium?","Ti","Sn","T","Sb","Science",2},
{"Ti is the chemical symbol for which element?","Titanium","Tin","Thorium","Thulium","Science",2},
{"Which part of the human body contains the most gold?","Toenails","Fingernails","Hair","Skin","Science",2},
{"W is the chemical symbol for which element?","Tungsten","Magnesium","Molybdenum","Manganese","Science",2},
{"Which planet in the Solar System is closest in size to Earth? ","Venus","Mercury","Mars","Uranus","Science",2},
{"What was the name of Jurij Gagarin's space capsule?","Vostok I","MIR","Sojus II","Sputnik I","Science",2},
{"Ergasiophobia is the fear of what?","Work","Flatulence","Odour","Belching","Science",2},
{"Which plant gives absinthe its hallucinogenic properties?","wormwood","mandrake","agara","belladonna","Science",2},
{"What kind of star is our sun?","Yellow Dwarf","Red Giant","Brown Dwarf","White Dwarf","Science",2},
{"How many stomachs does a moth have?",0,1,32,102,"Science",3},
{"Which percentage of the worlds population has an I.Q. of 120 or more ?","12.50%","1.20%","25.50%","48.50%","Science",3},
{"How many hearts does an earthworm have?",5,0,1,250,"Science",3},
{"How many 'arms' does a snowflake have?",6,5,8,9,"Science",3},
{"How many minutes does it take rays from the sun to reach the earth",8,6,10,12,"Science",3},
{"How many people have walked on the moon? ",12,9,6,3,"Science",3},
{"How many inches to a cubit?",18,16,12,21,"Science",3},
{"How many brains does a leech have?",32,0,1,102,"Science",3},
{"How many gallons of water can a camel drink in 10 minutes?",35,5,15,25,"Science",3},
{"How many muscles does it take to move your hand?",35,5,15,65,"Science",3},
{"How many cubic feet are there in three cubic yards?",81,9,144,27,"Science",3},
{"How many years is 1,000,000 hours?",114,111,211,214,"Science",3},
{"How many sq metres was ENIAC, the worlds first electronic computer?",170,70,7,770,"Science",3},
{"In which year was the ball point pen introduced?",1938,1958,1888,1908,"Science",3},
{"Ray Tomlinson sent the world's first email in which year?",1971,1981,1991,2001,"Science",3},
{"In which year was the first black tulip cultivated?",1986,1896,2006,1926,"Science",3},
{"How many hairs does the average human head have?","100,000","1,000,000","10,000","1,000","Science",3},
{"Roughly how many glasses of milk can one cow produce in one year?","120,000","520,000","20,000","720,000","Science",3},
{"What was the highest ever recorded temperature in the Libyan desert?","136 degrees Fahrenheit","180 degrees Fahrenheit","156 degrees Fahrenheit","236 degrees Fahrenheit","Science",3},
{"What is the speed of light?","186,272 miles per hour","184,272 miles per hour","286,272 miles per hour","1,188 ,272 miles per hour","Science",3},
{"In 1776 what was the average height of an Englishman?","5 ft 7 inches","5 ft 4 inches","6 foot","5 ft 1 inch","Science",3},
{"How long does the light from the sun take to reach the earth?","8.5 min","8.5 hours","8.5 sec","8.5 days","Science",3},
{"Bamboo plants can grow how many cm per day?","90cm","10cm","30cm","170cm","Science",3},
{"What is the most common blood group in Europe?","A +","A -","B +","O -","Science",3},
{"What does a nidoligist study?","Bird Nests","Waves","Clouds","Caves","Science",3},
{"Which of these elements is the heaviest?","Caesium","Rubidium","Potassium","Sodium","Science",3},
{"How many earths would fit inside the sun?","circa 1,000,000","circa 1,000","circa 10,000","circa 100,000","Science",3},
{"Hypermetropic people are what?","far sighted","obese","underfed","moody","Science",3},
{"Fredrick Sanger invented which life saver?","Insulin","Safety Pin","Inflatable Life Raft","Aspirin","Science",3},
{"Which of the following is a bird AND a fruit?","Kiwi","Juju","Mango","Pear","Science",3},
{"Which planet has the tallest mountain?","Mars","Earth","Jupiter","Venus","Science",3},
{"What does the medical term dolent mean?","pain","fever","numb","internal","Science",3},
{"Which of these is a name of a fish?","Parr","Aragon","Boleyn","Seymour","Science",3},
{"What is the only food a cockroach wont eat?","pickle","snail","marshmellow","porridge","Science",3},
{"What won't a cockroach eat?","pickles","porridge","curry","marmite","Science",3},
{"Which planet has the most eccentric orbit?","Pluto","Mercury","Earth","Venus","Science",3},
{"What is a Flemish Giant?","Rabbit","Star","Sprout","Mountain","Science",3},
{"A 'bind' is a group of what?","salmon","crows","zebras","cobras","Science",3},
{"Which planet has the most moons?","Saturn","Jupiter","Neptune","Uranus","Science",3},
{"Which bird has a record 25,000 feathers?","Swan","Goose","Albatross","Stork","Science",3},
{"Somatology is the study of what?","The Body","The Cosmos","Insects","Somalia","Science",3},
{"Who invented the sub-machine gun in 1920?","Thompson","Gattling","Colt","Winchester","Science",3},
{"Brontophobia is the fear of what?","Thunder","Skyscrapers","Elephants","The Dark","Science",3},
{"Which VW auto was not named after a wind?","Touran","Passat","Scirocco","Bora","Science",3},
{"A Blue Whale has a heart roughly the size of a what?","VW Beetle","Basketball","Grapefruit","Peanut","Science",3},
{"Anemophobia is the fear of what?","Wind","Spiders","The Dark","Fire","Science",3},
{"What is the more usual name for Roentgen Rays?","X Rays","Gamma Rays","Ultra Violet Rays","Magnetic Resonance","Science",3},
{"How many holes are there on a ten pin bowling ball?",3,4,2,5,"Sport",1},
{"How many rings on the Olympic flag?",5,4,6,7,"Sport",1},
{"How many Olympic gold medals did mark Spitz win in Munich in 1972?",7,8,6,5,"Sport",1},
{"How many lanes does an Olympic swimming pool have?",8,6,10,12,"Sport",1},
{"How many rounds are there in a professional boxing title contest?",12,10,20,8,"Sport",1},
{"In badminton, how many points win a single game?",15,20,10,19,"Sport",1},
{"Which 1982 World Cup team featured the talents of Zico, Socrates and Falcao?","Brazil","Italy","Spain","Argentina","Sport",1},
{"Which swimming stroke was not introduced to the Olympics until 1956?","Butterfly","Freestyle","Breaststroke","Doggy Style","Sport",1},
{"Which country has Zinedine Zidane played for?","France","Italy","Spain","Brazil","Sport",1},
{"In tennis, what name is given to winning the four major tournaments in a season?","Grand Slam","Outright","World Champion","Major Slam","Sport",1},
{"Which of these is another name for a golf course?","Links","Pitch","Steps","Suite","Sport",1},
{"Which tennis players nickname was 'The Rocket'?","Rod Laver","Fred Perry","Pete Sampras","John Newcombe","Sport",1},
{"Which sport is played in Roland Garros?","tennis","rugby","football","polo","Sport",1},
{"Which superstar was named 'The Great One'?","Wayne Gretsky","Rod Laver","Eddie Edwards","Dixie Dean","Sport",1},
{"What type of sportsman was the toy Stretch Armstrong dressed as?","Wrestler","Boxer","Archer","Cricketer","Sport",1},
{"How many Gold Medals did Jesse Owens win in the 1936 Berlin Olympics? ",4,3,5,6,"Sport",2},
{"How many hulls are there on a Catamaran?",4,3,2,1,"Sport",2},
{"How many balls are used in a game of croquet?",4,2,8,1,"Sport",2},
{"How many players are there in a polo team?",4,2,8,16,"Sport",2},
{"How many times did cyclist Miguel Indurain win the Tour de France in the 1990s?",5,9,2,"None","Sport",2},
{"How many games make up a match in squash?",5,10,12,8,"Sport",2},
{"How many players of an ice hockey team can be on the ice at the same time?",6,5,7,8,"Sport",2},
{"How many disciplines make up the men’s gymnastics competition at the Olympics?",6,8,10,4,"Sport",2},
{"What is the minimum number of points needed to win a game of squash?",9,10,20,15,"Sport",2},
{"How many players in a baseball team?",9,11,15,7,"Sport",2},
{"What number shirt did Pele usually wear when playing for Brazil?",10,9,8,1,"Sport",2},
{"How many players are there in a Hockey team?",11,15,9,10,"Sport",2},
{"In American Football, how many players from one team are allowed on the grid at any one time?",11,15,10,12,"Sport",2},
{"How many minutes of play are there in an American football match?",60,90,120,150,"Sport",2},
{"In which year did tennis legend 'Rocket' Rod Laver win his last Grand Slam?",1969,1977,1981,1958,"Sport",2},
{"Which city hosted the 1992 summer Olympic games?","Barcelona","Atlanta","Moscow","Seoul","Sport",2},
{"What did the dog named Pickles find?","Coupe Jules Rimet","Davis Cup","Federation Cup","F.A. Cup","Sport",2},
{"\"The ugliest salad bowl in the world\" is the nickname for which trophy?","Davis Cup","F.A. Cup","Ryder Cup","Football World Cup","Sport",2},
{"Wayne Gretzky was a superstar in which sport?","ice hockey","golf","tennis","boxing","Sport",2},
{"Which tennis player has not lost four Wimbledon singles finals?","Ivan Lendl","Jimmy Connors","Boris Becker","Ken Rosewall","Sport",2},
{"Who was the only tennis player to have won the US OPEN on three different surfaces?","Jimmy Conners ","Roger Federer ","Big Bill Tilden     ","Andre Agassi","Sport",2},
{"Mika Hakkinen was Formula 1 champion in 1998 and 1999 in which car?","McLaren-Mercedes","Ferrari","Renault","Benetton Ford","Sport",2},
{"'El tri' is the nickname for which national football team? ","Mexico","Brazil","Spain","Switzerland","Sport",2},
{"Which summer Olympic Games were boycotted by most African countries?","Montreal 76","Moscow 80","Munich 72","USA 84","Sport",2},
{"Jacky Ickx was a superstar in which sport?","motor racing","cycling","soccer","tennis","Sport",2},
{"Every player in the Bulgarian national team at the 1994 Football World Cup had a name ending in which letters?","ov","ki","us","an","Sport",2},
{"Which country has won a record four World Championships in mens field hockey?","Pakistan","Germany","Holland","Ireland","Sport",2},
{"80% of all the footballs in the world are made in which country?","Pakistan","USA","Mexico","Australia","Sport",2},
{"Who was the last man to win the Grand Slam in tennis?","Rod Laver","Bjorn Borg","Roger Federer","Ivan Lendl","Sport",2},
{"Which stadium is named after a WW I flying ace?","Roland Garros","Giuseppe Meazza","Fratton Park","Bernabeu","Sport",2},
{"Which city saw Steffi Graf win Olympic gold?","Seoul","Barcelona","Los Angeles","Moscow","Sport",2},
{"'Wedel' is a term in which sport?","Skiing","Darts","Chess","Formula One","Sport",2},
{"In golf what name is given to the No 3 wood?","Spoon","Knife","Fork","Ladel","Sport",2},
{"Which woman thrashed her opponent 6-0 6-0 in the 1988 French Open final?","Stefi Graf","Venus Williams","Billy Jean King","Virginia Wade","Sport",2},
{"What weighs 4lb 6oz at the Olympics?","The Discuss","The Javelin","The Olympic Torch","The Medals (Gold, Silver, Bronze)","Sport",2},
{"Which football world cup had the highest average attendance figures?","USA 94","Brazil 50","England 66","Italy 90","Sport",2},
{"If a golf hole is 130 yards long, what would its par be?",3,2,4,5,"Sport",3},
{"How many laps are completed to win a speedway race?",4,5,6,10,"Sport",3},
{"How many baseball gloves can be made with the leather from one cow?",5,1,25,55,"Sport",3},
{"How old was Boris Becker when he won his first Wimbledon singles title?",17,16,15,18,"Sport",3},
{"How many Wimbledon titles did Billie Jean King win?",20,30,10,5,"Sport",3},
{"How many laps are run in a 10000-meter track race?",25,20,30,35,"Sport",3},
{"In which year were the summer Olympic games in Berlin? ",1936,1932,1942,1948,"Sport",3},
{"In which year were the summer olympic games in Montreal? ",1976,1980,1974,1978,"Sport",3},
{"In which year were the summer Olympic games in Moscow?",1980,1982,1978,1976,"Sport",3},
{"Countries from which continent boycotted the 1976 summer Olympics in Montreal?","Africa","Europe","Asia","South  America","Sport",3},
{"Who was the first black woman to win both the US Open and Wimbledon?","Althea Gibson","Venus Williams","Shirley Fry","Serena Williams","Sport",3},
{"Who is not an accomplished fencer?","Arnold Schwarzenegger","Gene Wilder","Elijah Wood","Antonio Banderas","Sport",3},
{"Which sport do the Minnesota Twins play?","Baseball","Ice Hockey","Basketball","Football","Sport",3},
{"Who was the first American to win the mens singles title at Wimbledon?","Big Bill Tilden","Donald Budge","Jack Kramer","Bobby Riggs","Sport",3},
{"Which NHL superstar had the nickname 'The Golden Jet'?","Bobby Hull","Bobby Orr","Gordie Howe","Stan Mikita","Sport",3},
{"Figure skating champion Elvis Stojko was from which country?","Canada","Russia","USA","Bulgaria","Sport",3},
{"Who was the captain of Brazil when they won the 1970 football world cup?","Carlos Alberto","Pele","Romario","Socrates","Sport",3},
{"Eddy Merckx was a superstar in which sport?","cycling","soccer","tennis","baseball","Sport",3},
{"Who has a black belt in judo?","David Lee Roth","Bill Gates","David Beckham","Prince Charles","Sport",3},
{"Nine time Olympic gold medal winner Paavo Nurmi was from which country?","Finland","Russia","India","Hungary","Sport",3},
{"Juan Manuel Fangio was a superstar in which sport in the 1950s?","formula one","tennis","baseball","soccer","Sport",3},
{"In which sport does one compete for the Stanley Cup?","ice hockey","polo","golf","squash","Sport",3},
{"Which poem greets contestants to center court Wimbledon?","If","All the worlds a stage","The road not taken","A dream within a dream","Sport",3},
{"Who does not have a black belt in karate?","Jennifer Lopez","Sharon Stone","Chuck Norris","Guy Ritchie","Sport",3},
{"What was the name of the mascot bear at the 1980 summer Olympic games in Moscow?","Mischa","Olga","Igor","Nikita","Sport",3},
{"Which NHL hockey team has won the most Stanley Cups?","Montreal Canadiens","Toronto Maple Leafs","Boston Bruins","New York Rangers","Sport",3},
{"At which Formula One circuit would one find the 'Lesmo Bend'?","Monza","Circuit Gilles Villeneuve","Hockenheimring","Silverstone","Sport",3},
{"Speed skating originated in which country?","Netherlands","Canada","Norway","Russia","Sport",3},
{"Which professional sport awards the Lady Byng Memorial Trophy each year for the 'Most Gentlemanly Player'?","NHL","NFL","PGA","NBA","Sport",3},
{"'Nati' is the nickname for which country's football team?","Switzerland","South Korea","Holland","Mexico","Sport",3},
{"Gossima was the original name for which sport?","Table Tennis","Lawn Tennis","Badminton","Snooker","Sport",3},
{"Lew Hoad was a superstar in which sport in the 1950s?","tennis","ice hockey","baseball","soccer","Sport",3},
{"A 'Miller' is a move in which sport?","Trampolining","Diving","Chess","Ice Hockey","Sport",3},
{"Which superstar wore the number 99 ?","Wayne Gretzky","Zidane","Dixie Dean","Sebastian Coe","Sport",3}
}
